### ISSUE TITLE
SDWebImage不指定版本号，或者使用~>符号，如何处理？

### ISSUE THREAD

**Issue by miroda** [MeetYouDevs/cocoapods-imy-bin#100]
SDWebImage不指定版本号，或者使用~>符号进行安装的时候，就会出现pod安装的版本号和私有源中的版本不一致，导致找不到版本的情况出现，请问这种情况如何处理？

pod 'SDWebImage', '~>5.9.4'
pod 'SDWebImage'

`[!] CocoaPods could not find compatible versions for pod "SDWebImage":
  In snapshot (Podfile.lock):
    SDWebImage (= 5.10.2)

  In Podfile:
    Demo (from `../../../ccbindemo/Demo.podspec`) was resolved to 1, which depends on
      SDWebImage

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `SDWebImage` inside your development pod `Demo`.
   You should run `pod update SDWebImage` to apply changes you've made.
`

**Comment by dabing1022** [comment]
私有源中的版本是啥？

**Comment by miroda** [comment]
私有源中还么有这个版本呢

**Comment by dabing1022** [comment]
源码私有源要先有，二进制私有源打完二进制会自动更新进去

**Comment by miroda** [comment]
流程是，我先pod install，安装5.10.2到本地，然后pod bin auto --all-make 这样子吗？
源码私有源，指的是什么？项目的源码吗

**Comment by dabing1022** [comment]
提供podfile podspec

**Comment by miroda** [comment]
Pod::Spec.new do |s|
	s.name = 'Demo'
	s.version = '1'
	s.description = '我只是一个测试的，主要是想要 s.dependency'
	s.license = 'MIT'
	s.summary = 'Seeyou'
	s.homepage = 'https://github.com/meiyoudev/IMYPublic'
	s.authors = { 'suliangjin' => 'suliangjin@xiaoyouzi.com' }
	s.source = { :git => 'git@github.com:su350380433/cocaopods-imy-bin.git', :branch => 'dev' }
        s.requires_arc = true
        s.ios.deployment_target = '9.0'
        s.source_files = 'Source/**/*.{h,m,c}'
        s.public_header_files = 'Source/**/*.h'

        s.dependency 'Masonry'
        s.dependency 'FMDB'
        # s.dependency 'SocketRocket'
        s.dependency 'MJExtension','3.2.1'
        s.dependency 'SDWebImage','5.10.2'

end

**Comment by dabing1022** [comment]
`pod 'SDWebImage', '~>5.9.4' `这个是在哪里写的？Podfile么？

**Comment by miroda** [comment]
Podfile
source 'https://github.com/cocoapods/specs.git'

target 'Demo' do
  pod 'FMDB'  
  pod 'Masonry'
  # pod 'SocketRocket'
  pod 'MJExtension','3.2.1'
  pod 'SDWebImage','5.10.2'
  end

**Comment by miroda** [comment]
不指定版本号，不好处理，我先指定了一下版本好

**Comment by dabing1022** [comment]
打包的时候最好指定下版本

**Comment by miroda** [comment]
现在已经指定版本了,一直报错

[!] CocoaPods could not find compatible versions for pod "SDWebImage":
  In snapshot (Podfile.lock):
    SDWebImage (= 5.10.2)

  In Podfile:
    Demo (from `../../../ccbindemo/Demo.podspec`) was resolved to 1, which depends on
      SDWebImage (= 5.10.2)

None of your spec sources contain a spec satisfying the dependencies: `SDWebImage (= 5.10.2), SDWebImage (= 5.10.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by dabing1022** [comment]
先尝试`pod repo update`

**Comment by miroda** [comment]
[!] ===【 SDWebImage | 5.10.2 】二进制组件制作完成 ！！！
