### ISSUE TITLE
私有库如何处理

### ISSUE THREAD

**Issue by miroda** [MeetYouDevs/cocoapods-imy-bin#101]
请问类似这样的库，如何处理？
`pod 'ZXXPrint',:git => 'git@gitlab.ops.zxx.com/zxxprint.git', :tag => '0.0.1'`

直接写到podfile里面之后，会报
[!] Unable to find a specification for 'ZXXPrint'.

**Comment by CY-0227** [comment]
同问，请问怎么处理

**Comment by iOSGL** [comment]
也碰到了相同的问题， 找不到specification
