### ISSUE TITLE
无法生成头文件

### ISSUE THREAD

**Issue by miroda** [MeetYouDevs/cocoapods-imy-bin#104]
pod 'WCDB'
pod 'SQLiteRepairKit'
无法生成头文件

**Comment by miroda** [comment]
@dabing1022 你最新的pr我已经合并了，这个库帮忙看下，这个是C语言的 库

**Comment by miroda** [comment]
<img width="634" alt="企业微信20210120-155249@2x" src="https://user-images.githubusercontent.com/2841126/105144017-9836f700-5b37-11eb-95dc-c166626526da.png">

**Comment by miroda** [comment]
可以看到本地打包的是没有问题的，但是后面pod bin install 的时候就不行了

**Comment by dabing1022** [comment]
> 可以看到本地打包的是没有问题的，但是后面pod bin install 的时候就不行了

打包的二进制看下是否正常？（包括头文件、二进制等文件）具体怎么不行呢？咱们描述问题的时候注意描述清楚，为他人节省反复询问的时间。😂

**Comment by miroda** [comment]
1、打包之后，本地的目录里面是有头文件的
2、上传到nodejs的服务器里面的zip包也是有头文件的
3、pod bin install之后，xcode工程中，就没有头文件了

**Comment by dabing1022** [comment]
1. Podfile中如何指定WCDB的？
2. 工程Pods/WCDB中是怎么显示的？

**Comment by miroda** [comment]
<img width="316" alt="企业微信20210121-132012@2x" src="https://user-images.githubusercontent.com/2841126/105283432-6da67600-5beb-11eb-837f-ca4329331b0d.png">

**Comment by miroda** [comment]
WCDB现在在xcode工程中又有头文件，现在是 SQLiteRepairKit没有头文件

**Comment by miroda** [comment]
SQLiteRepairKit是
pod 'PolyvVodSDK', '~>2.13.1'
中s.denpendency这样的方式指定的

**Comment by dabing1022** [comment]
你用的imy-bin版本是啥？

**Comment by miroda** [comment]
master版本，已经合并了你最新提交的代码

**Comment by dabing1022** [comment]
我测试下 SQLiteRepairKit 这个库，稍后回复。

**Comment by miroda** [comment]
WCDB中引用SQLiteRepairKit的方式
` "dependencies": {
    "WCDBOptimizedSQLCipher": [
      "~> 1.2.0"
    ],
    "SQLiteRepairKit": [
      "~> 1.2.0"
    ]
  },`

**Comment by dabing1022** [comment]
![image](https://user-images.githubusercontent.com/1892303/105284312-27521680-5bed-11eb-8e08-90d08bd798ea.png)

正常生成的lib里面有头文件

**Comment by miroda** [comment]
我这边生成的也是有的，传到弄的js里面的也是有的，就是工程里面没有
<img width="391" alt="企业微信20210121-133350@2x" src="https://user-images.githubusercontent.com/2841126/105284406-549ec480-5bed-11eb-80d1-834fe40659de.png">

**Comment by dabing1022** [comment]
![Uploading image.png…]()

**Comment by miroda** [comment]
～/Library/Caches/CocoaPods/Pods/Release/SQLiteRepairKit/1.2.2-a4e19
<img width="870" alt="企业微信20210121-133633@2x" src="https://user-images.githubusercontent.com/2841126/105284553-b101e400-5bed-11eb-997c-36d5162847f5.png">

**Comment by miroda** [comment]
这样的操作方式会导致我自己写的一个库的头文件无法出现
#!/bin/bash
rm *.lock
pod bin install

而一下的方式就没有问题
#!/bin/bash
rm *.lock
pod install
pod bin install

**Comment by miroda** [comment]
@dabing1022 你可否用这两个库来测试

   pod 'PolyvVodSDK', '~>2.13.1'
    pod 'PLVSubtitle'

**Comment by miroda** [comment]
@dabing1022 找到了问题，在你之前提交fix 无法生成头文件的代码到master，我打的老的库，缓存在了～/Library/Caches/CocoaPods/Pods/SQLiteRepairKit目录下，导致无法更新最新的库，这个问题会造成无法生成头文件
