### ISSUE TITLE
执行pod bin auto 报错

### ISSUE THREAD

**Issue by kk-laoguo** [MeetYouDevs/cocoapods-imy-bin#105]
### `pod bin auto`报错如下：
请问如何解决，还是我哪里操作有问题?

 zainguo@zaindeMacBook-Pro  ~/Desktop/BinaryTest  pod bin auto
/Users/zainguo/Desktop/BinaryTest/binary-server
/Users/zainguo/Desktop/BinaryTest/BinaryTest.xcodeproj
/Users/zainguo/Desktop/BinaryTest/BinaryTest.xcworkspace
/Users/zainguo/Desktop/BinaryTest/Pods
/Users/zainguo/Desktop/BinaryTest/Podfile
/Users/zainguo/Desktop/BinaryTest/BinaryTest
/Users/zainguo/Desktop/BinaryTest/Podfile.lock

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod bin auto
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : aliyun-cxbinarybinsource - git - git@code.aliyun.com:zainguo/CXBinaryBinSource.git @ 797ebb981f10bd425684d980678f8aec56ba9f55

               aliyun-cxbincodesource - git - git@code.aliyun.com:zainguo/CXBinCodeSource.git @ bf001f9676363fdc680fb3012376c4453daf3cda

               aliyun-zainguo-cxbinarybinsource - git - https://code.aliyun.com/zainguo/CXBinaryBinSource.git @ 441e74109372336991049a549925522ceb9d8fa2

               aliyun-zainguo-cxbincodesource - git - https://code.aliyun.com/zainguo/CXBinCodeSource.git @ bf001f9676363fdc680fb3012376c4453daf3cda

               CaiXinRepo - git - https://code.aliyun.com/340435371/CaiXinRepo.git @ 4393dcf04e9069759574a750bfb9127eb6eab60f

               cocoapods - git - https://github.com/CocoaPods/Specs.git @ 0145d12ebb4a554a44692d380d59edfd91c1be02

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.1
cocoapods-imy-bin                     : 0.3.0.11
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BinaryTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '4.2.0'
  pod 'DefaultsKit'
  # Pods for BinaryTest

end
```

### Error

```
TypeError - no implicit conversion of Array into String
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/specification.rb:705:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/specification.rb:705:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/specification.rb:705:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=no+implicit+conversion+of+Array+into+String&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Can't specify same configuration for two pods if one is in abstract_target and the other is inside, in a target
   https://github.com/CocoaPods/CocoaPods/issues/8732 [open] [1 comment]
   07 May 2019

 - pod install abstract_target with plugin cocoapods-binary cause TypeError - no implicit conversion of Array into String
   https://github.com/CocoaPods/CocoaPods/issues/8660 [closed] [3 comments]
   01 Apr 2019

 - TypeError - no implicit conversion of Array into String
   https://github.com/CocoaPods/CocoaPods/issues/7421 [closed] [59 comments]
   24 Feb 2018

and 4 more at:
https://github.com/cocoapods/cocoapods/search?q=no%20implicit%20conversion%20of%20Array%20into%20String&type=Issues&utf8=✓

### 工程目录如下：

![project](https://gitee.com/Tangchi/ZainPhotoCloud/raw/master/blogimage/20210121222319.png)

**Comment by SouthSnow** [comment]
我也遇到同样的问题

**Comment by dabing1022** [comment]
仔细阅读下文档 跑下作者的demo项目 imy-bin要求podspec podfile一个文件夹中 不是在pod example工程直接打包的

**Comment by miroda** [comment]
对，你需要新建podspec一个文件

**Comment by PggMan** [comment]
我这里遇到了同样问题，命令是在Poffile同级目录下执行，但是报了同样错误。至于三楼说的podspec文件我有些不裂解。你的意思是在pod lib creat生成的库制作模板中执行的吗？
