### ISSUE TITLE
近期会支持swift项目，做个小调查，你们项目使用use_frameworks! 吗？

### ISSUE THREAD

**Issue by su350380433** [MeetYouDevs/cocoapods-imy-bin#11]
近期会支持swift项目，做个小调查，你们项目使用`use_frameworks! `吗？

**Comment by dlxxl06** [comment]
我们就是纯swift 开发的

**Comment by su350380433** [comment]
> 我们就是纯swift 开发的

Podfile 使用了use_frameworks! 吗？

**Comment by 347008893** [comment]
swift oc混合开发 不使用use_frameworks

**Comment by su350380433** [comment]
> swift oc混合开发 不使用use_frameworks



> swift oc混合开发 不使用use_frameworks

混合的是OC多呢，还是Swift部分多？

**Comment by 347008893** [comment]
swift 居多

**Comment by 347008893** [comment]
能否建个群啊？ 方便大家一起讨论

**Comment by su350380433** [comment]
> swift 居多

swift多的改为use_frameworks!也方便

**Comment by 347008893** [comment]
还有那种针对 :modular_headers => true 的有点无解

**Comment by su350380433** [comment]
看起来这套系统没几个人有需要的样子，没什么动力去研发了~

**Comment by su350380433** [comment]
发现swift有个好玩的，不管是否使用了use_frameworks!，都有办法支持。
所以，这个调查也无关紧要了~

**Comment by su350380433** [comment]
大家都不怎么活跃啊，还是我们的这个项目在大家那边不适用呢~
给点继续做下去的动力~

**Comment by su350380433** [comment]
> 发现swift有个好玩的，不管是否使用了use_frameworks!，都有办法支持。
> 所以，这个调查也无关紧要了~

无视混合还是纯swift开发，都能支持

**Comment by 347008893** [comment]
老哥 准备近期开出相关功能？

**Comment by su350380433** [comment]
> 老哥 准备近期开出相关功能？

在做实验中，实现了部分功能。
没什么动力~

**Comment by 347008893** [comment]
加油~  毕竟刚开始，目前使用的人并不是很多

**Comment by Decsunshine** [comment]
我们团队的项目会用到 Swift 和 OC 混编，求支持

**Comment by su350380433** [comment]
> 我们团队的项目会用到 Swift 和 OC 混编，求支持

功能已经开发完成了，目前在适配一些环境。

**Comment by Motivationlrx** [comment]
请教下cocoapods 使用的use_frameworks! :linkage => :static这样也可以将pods库打包为静态库，那区别在哪里呢，我这边测试使用use_frameworks! :linkage => :static 命令，在子库中引入了直接导入了一个OC框架，在壳工程也直接导入了，两者重复会出现冲突，原先动态库的时候两者是隔离的，没有出现这样的报错问题。
我们现在项目是用的swift模块化，动态库太多，启动时间大半都是花在动态库链接上，我现在也在想怎么样都修改成静态库，只不过资源加载方法这些需要替换。

**Comment by motaionx** [comment]
@su350380433

**Comment by su350380433** [comment]
纯swift、swift-oc 混编项目已支持

**Comment by Serlight** [comment]
使用use_modular_header!
