### ISSUE TITLE
pod bin auto 报错

### ISSUE THREAD

**Issue by miroda** [MeetYouDevs/cocoapods-imy-bin#116]
执行上面的命令之后，会生成错误的 podspec.json文件，其路径在
xx-build-temp/bin-archive/app/Pods/Local Podspecs目录下；
内容为
{
  "name": "Tracking",
  "version": "1.1.1",
  "summary": "A short description of AXXTracking.",
  "description": "TODO: Add long description of the pod here.",
  "homepage": "https://github.com/mirodaTracking",
  "license": {
    "type": "MIT",
    "file": "LICENSE"
  },
  "source": {
    "git": "https://github.com/miroda/AXXTracking.git",
    "tag": "1.1.1"
  },
  "platforms": {
    "ios": "9.0"
  },
  "source_files": "AXXTracking/Classes/**/*",
  "dependencies": {
    "Reachability": [

    ]
  }
}

可是我实际的pod地址不是https://github.com/miroda/Tracking。
所以pod就无法下载这个库，然后执行build操作的时候就会报错，找不到这个库，所以生成这个库的时候有bug

**Comment by dabing1022** [comment]
Tracking这库的地址，你要核查下，你要打的版本，对应的podspec文件中的source的地址。

**Comment by miroda** [comment]
自动生成的yaml文件里面的地址是对的，但是在podspec.json文件里面的地址都是错的

**Comment by dabing1022** [comment]
你提供下 Tracking tag为1.1.1的podspec文件

**Comment by miroda** [comment]
s.dependency 'AXXTracking'

**Comment by miroda** [comment]
Resolver中将这个库认定为有二进制的库，没有采用源码依赖，这是导致这个问题的核心

**Comment by miroda** [comment]
实际上并没有二进制

**Comment by miroda** [comment]
@dabing1022 问题找到了，本地的二进制私有源库中还有这个库之前的记录，pod bin update 更新就可以了
