### ISSUE TITLE
code_repo_url只能配置一个吗？

### ISSUE THREAD

**Issue by Allen-King** [MeetYouDevs/cocoapods-imy-bin#12]
现在工程里使用了多个源码的source在使用pod bin local的时候是跑不起来的，是使用的问题吗？

**Comment by su350380433** [comment]
多个的话，可以在podfile 中添加 source里面，影响不大

**Comment by iOSLR** [comment]
> 多个的话，可以在podfile 中添加 source里面，影响不大

请问一下具体的操作是什么样的
