### ISSUE TITLE
pod bin auto 报错

### ISSUE THREAD

**Issue by iOSLR** [MeetYouDevs/cocoapods-imy-bin#14]
[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=no+implicit+conversion+of+Array+into+String&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Can't specify same configuration for two pods if one is in abstract_target and the other is inside, in a target
   https://github.com/CocoaPods/CocoaPods/issues/8732 [open] [1 comment]
   07 May 2019

 - pod install abstract_target with plugin cocoapods-binary cause TypeError - no implicit conversion of Array into String
   https://github.com/CocoaPods/CocoaPods/issues/8660 [closed] [3 comments]
   01 Apr 2019

 - TypeError - no implicit conversion of Array into String
   https://github.com/CocoaPods/CocoaPods/issues/7421 [closed] [59 comments]
   24 Feb 2018

and 4 more at:

**Comment by su350380433** [comment]
兄弟，来点更详细的信息

**Comment by hengyangKing** [comment]
### Error

```
TypeError - no implicit conversion of Array into String
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:664:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:664:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:664:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by fengshuo1992** [comment]
我也是遇到这个问题

**Comment by miroda** [comment]
我也是遇到这个问题
