### ISSUE TITLE
pod bin auto --all-make 出现“组件二进制版本编译失败”，希望得到帮助

### ISSUE THREAD

**Issue by lijiaxiang** [MeetYouDevs/cocoapods-imy-bin#146]
viper@bogon  ~/Downloads/cocoapods-imy-bin-demo-master/Demo  pod bin auto --all-make
Ignoring psych-3.3.0 because its extensions are not built. Try: gem pristine psych --version 3.3.0
/Users/viper/Downloads/cocoapods-imy-bin-demo-master/Demo/Demo.xcodeproj
/Users/viper/Downloads/cocoapods-imy-bin-demo-master/Demo/Demo
/Users/viper/Downloads/cocoapods-imy-bin-demo-master/Demo/BinArchive.json
/Users/viper/Downloads/cocoapods-imy-bin-demo-master/Demo/.DS_Store
/Users/viper/Downloads/cocoapods-imy-bin-demo-master/Demo/Podfile_local
/Users/viper/Downloads/cocoapods-imy-bin-demo-master/Demo/Demo_test.podspec
====== cocoapods-imy-bin 0.3.1.2 版本 ========

======  dev 环境 ========

======  dev 环境 ========

Generating Demo in `../Demo-build-temp/bin-archive/Demo`
Open `../Demo-build-temp/bin-archive/Demo/Demo.xcworkspace` to work on Demo
Building static framework Demo (1)
Building static framework AFNetworking (4.0.1)
fatal error: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: build-arm64/libAFNetworking.a (No such file or directory)
framework没有文件：ios/AFNetworking.framework/Versions/A/AFNetworking
Building static framework KVOController (1.2.0)
fatal error: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: build-arm64/libKVOController.a (No such file or directory)
framework没有文件：ios/KVOController.framework/Versions/A/KVOController

Updating Spec Repositories

更新私有源仓库 inf_example_spec_bin_dev
更新私有源仓库 inke-platformspecs
  $ /usr/bin/git -C /Users/viper/.cocoapods/repos/inke-platformspecs fetch origin --progress
  $ /usr/bin/git -C /Users/viper/.cocoapods/repos/inf_example_spec_bin_dev fetch origin --progress
  $ /usr/bin/git -C /Users/viper/.cocoapods/repos/inf_example_spec_bin_dev rev-parse --abbrev-ref HEAD
  $ /usr/bin/git -C /Users/viper/.cocoapods/repos/inke-platformspecs rev-parse --abbrev-ref HEAD
  master
  master
  $ /usr/bin/git -C /Users/viper/.cocoapods/repos/inf_example_spec_bin_dev reset --hard origin/master
  $ /usr/bin/git -C /Users/viper/.cocoapods/repos/inke-platformspecs reset --hard origin/master
  HEAD is now at 8c7ea77 [Add] YYCache (1.0.4)
  HEAD is now at 3906444 [Update] IKLog (1.0.5)

[!] ====== cocoapods-imy-bin 0.3.1.2 版本 ========

[!] ======  dev 环境 ========

[!] ====== archive-white-pod-list = ["Demo", "YYCache"]

[!] ====== ignore_git_list = ["git@gitlab.xxx.com:Github-iOS"]

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

[!] 【AFNetworking | 4.0.1】组件二进制版本编译失败 .

[!] 【KVOController | 1.2.0】组件二进制版本编译失败 .

**Comment by SouthSnow** [comment]
请问怎么解决的

**Comment by zealforbeing** [comment]
同样的问题，请问是如何解决的？
