### ISSUE TITLE
打出的.a类型不正确

### ISSUE THREAD

**Issue by Joachim001** [MeetYouDevs/cocoapods-imy-bin#15]
在Podfile中设置了release_iphoneos，但是打出来的.a显示：Architectures in the fat file: /Users/XXX/Desktop/libKSCrash.a are: armv7 x86_64 arm64,我看文章上说release_iphoneos模式下不包含x86_64，那是不是制作二进制时指定编译环境没有生效呢？还有就是正常的话debug_iPhoneos和release_iphoneos都是不包含x86_64的，那我该如何区分打出来的.a是debug_iPhoneos还是release_iphoneos环境的呢（是不是我指定的编译环境）？

**Comment by su350380433** [comment]
设置下环境，老兄，看下命令 --help

**Comment by Joachim001** [comment]
我设置了环境的set_configuration_env('release_iphoneos')
pod bin auto --all-make执行后会出现如下现象：
<img width="391" alt="image" src="https://user-images.githubusercontent.com/44601677/88777158-79bff680-d1b9-11ea-84c7-2aaa13eccb92.png">
<img width="431" alt="image" src="https://user-images.githubusercontent.com/44601677/88777182-817f9b00-d1b9-11ea-83aa-0a0afeb61605.png">
我起初看到灰色的文字 我以为我的环境设置生效了呢 但是后来结果显示还是黄色的生效了

**Comment by Joachim001** [comment]
set_configuration_env('release_iphoneos')
我在podfile里面这么设置的，那么打出来的.a应该不能在模拟器上运行吧，因为release不包含x86_64，但是我在模拟器上运行是可以的，这个是因为啥呢？

**Comment by Joachim001** [comment]
大佬 能说明下么
