### ISSUE TITLE
修改了binary_download_url，但默认下载还是localhost

### ISSUE THREAD

**Issue by CY-0227** [MeetYouDevs/cocoapods-imy-bin#151]
修改了binary_download_url为 http://192.168.31.120:5000/frameworks/%s/%s/zip，源码中default也修改了，但是制作的时候还是从localhost:8080下载，请问怎么回事？

bin_dev.yml文件中看到也已经修改了

[!] Error installing MJExtension
[!] /usr/bin/curl -f -L -o /var/folders/f6/yfkswwnx0z3gzrjcjrsd_1hr0000gn/T/d20210428-59263-v748o2/file.zip http://localhost:8080/frameworks/MJExtension/3.2.4/zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 8080: Connection refused

**Comment by CY-0227** [comment]
已解决

**Comment by TonyReet** [comment]
> 已解决

请问怎么解决的

**Comment by looha518** [comment]
> 已解决

大佬 请问是怎么解决的

**Comment by looha518** [comment]
> > 已解决
> 
> 请问怎么解决的

你好 你解决了吗？
