### ISSUE TITLE
db和服务起好了，但制作二进制失败

### ISSUE THREAD

**Issue by xiaojiekillua** [MeetYouDevs/cocoapods-imy-bin#158]
db和服务都起起来了，制作二进制总是失败
报TypeError - no implicit conversion of nil into String
请问是啥情况呢

**Comment by looha518** [comment]
你好 这个问题怎么解决的？ruby退回了吗？

**Comment by CveniEs** [comment]
大佬解决了嘛

**Comment by looha518** [comment]
> 大佬解决了嘛

https://github.com/MeetYouDevs/cocoapods-imy-bin/issues/159
