### ISSUE TITLE
pod bin auto --all-make，本地服务文件上传成功，最后结果：组件spec push失败。

### ISSUE THREAD

**Issue by looha518** [MeetYouDevs/cocoapods-imy-bin#162]
各位大佬，帮忙给看看，卡几天了，跪谢啊！pod bin auto --all-make，loohaBin-build-temp文件夹下.a文件和zip文件都正常合成了，本地服务文件上传成功，但是最后结果还是：组件spec push失败。

# **Podfile文件：**

source 'https://github.com/CocoaPods/Specs.git'
plugin 'cocoapods-imy-bin'
use_binaries!

target 'loohaBin' do
   pod 'HXPhotoPicker'
   pod 'AFNetworking'

end

# **podspec文件：**
 MARK: converted automatically by spec.py. @hgy

Pod::Spec.new do |s|
	s.name = 'loohaBin'
	s.version = '1'
	s.description = '我只是一个测试的，主要是想要 s.dependency'
	s.license = 'MIT'
	s.summary = 'Seeyou'
	s.homepage = 'https://github.com/looha518/mba_bin'
	s.authors = { 'suliangjin' => 'suliangjin@xiaoyouzi.com' }
	s.source = { :git => 'https://github.com/looha518/mba_bin_source.git', :branch => 'master' }
        s.requires_arc = true
        s.ios.deployment_target = '9.0'
        s.source_files = 'Source/**/*.{h,m,c}'
        s.public_header_files = 'Source/**/*.h'

        s.dependency 'HXPhotoPicker'
        s.dependency 'AFNetworking'
end

# **BinArchive.json文件：**
{
    "//":"archive-white-pod-list  制作二进制白名单",
    "archive-white-pod-list" : [
        "loohaBin"
    ],
    "ignore-git-list": [
    ],
    "ignore-http-list": [
    ]
}
   
### **终端执行 pod bin auto --all-make后：**

/Users/looha/Desktop/WeChat/loohaBin/loohaBin.xcworkspace
/Users/looha/Desktop/WeChat/loohaBin/BinArchive.json
/Users/looha/Desktop/WeChat/loohaBin/.DS_Store
/Users/looha/Desktop/WeChat/loohaBin/loohaBinUITests
/Users/looha/Desktop/WeChat/loohaBin/loohaBin
/Users/looha/Desktop/WeChat/loohaBin/Pods
/Users/looha/Desktop/WeChat/loohaBin/loohaBin.podspec
====== cocoapods-imy-bin 0.3.1.3 版本 ========

======  dev 环境 ========

======  dev 环境 ========
[pod gen] Running with `pod gen` configuration {
  podfile_path: /Users/looha/Desktop/WeChat/loohaBin/Podfile,
  podfile: Podfile,
  use_podfile: true,
  use_podfile_plugins: true,
  podfile_plugins: {"cocoapods-imy-bin"=>{}},
  lockfile: #<Pod::Lockfile>,
  use_lockfile: true,
  use_lockfile_versions: true,
  use_libraries: true,
  generate_multiple_pod_projects: false,
  incremental_installation: false,
  gen_directory: /Users/looha/Desktop/WeChat/loohaBin-build-temp/bin-archive,
  auto_open: false,
  clean: true,
  podspec_paths: [#<Pathname:/Users/looha/Desktop/WeChat/loohaBin/loohaBin.podspec>, #<Pathname:/Users/looha/Desktop/WeChat/loohaBin/loohaBin.podspec>],
  podspecs: [#<Pod::Specification name="loohaBin">, #<Pod::Specification name="loohaBin">],
  sources: ["https://github.com/looha518/mba_bin.git", "https://github.com/looha518/mba_bin_source.git", "https://github.com/looha518/mba_bin.git", "https://github.com/looha518/mba_bin_source.git", "https://cdn.cocoapods.org"],
  local_sources: [],
  repo_update: false,
  use_default_plugins: false,
  deterministic_uuids: false,
  share_schemes_for_development_pods: true,
  warn_for_multiple_pod_sources: false,
  use_modular_headers: false }

Generating loohaBin in `../loohaBin-build-temp/bin-archive/loohaBin`
    Cleaning gen install directory
    Creating stub application
    Writing Podfile

Installing...
Installing AFNetworking (4.0.1)
Installing HXPhotoPicker (3.2.1)
Installing loohaBin (1)

[!] Please close any current Xcode sessions and use `loohaBin.xcworkspace` for this project from now on.
Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.

Performing post-installation steps
    Open `../loohaBin-build-temp/bin-archive/loohaBin/loohaBin.xcworkspace` to work on loohaBin

Building static framework loohaBin (1)
  command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  ARCHS='arm64' OTHER_CFLAGS='-fembed-bitcode
  -Qunused-arguments'
  CONFIGURATION_BUILD_DIR=/Users/looha/Desktop/WeChat/loohaBin-build-temp/bin-archive/loohaBin/build-arm64 clean build
  -configuration Debug -target loohaBin -project ./Pods/Pods.xcodeproj 2>&1
  command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  ARCHS='armv7' OTHER_CFLAGS='-fembed-bitcode
  -Qunused-arguments'
  CONFIGURATION_BUILD_DIR=/Users/looha/Desktop/WeChat/loohaBin-build-temp/bin-archive/loohaBin/build-armv7 clean build
  -configuration Debug -target loohaBin -project ./Pods/Pods.xcodeproj 2>&1
  Building simulator libraries
  command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  -sdk iphonesimulator ARCHS='x86_64'
  CONFIGURATION_BUILD_DIR=/Users/looha/Desktop/WeChat/loohaBin-build-temp/bin-archive/loohaBin/build-x86_64 clean
  build -configuration Debug -target loohaBin -project ./Pods/Pods.xcodeproj 2>&1

Building static framework AFNetworking (4.0.1)

Building static Library AFNetworking (4.0.1)
  Building ios libraries with archs ["arm64", "armv7"]
  lipo -create -output ios/AFNetworking.framework/Versions/A/AFNetworking build-arm64/libAFNetworking.a
  build-armv7/libAFNetworking.a build-x86_64/libAFNetworking.a
  Copying license

Building static library AFNetworking (4.0.1)
Compressing bin_AFNetworking_4.0.1 into bin_AFNetworking_4.0.1.zip

Building static framework HXPhotoPicker (3.2.1)

Building static Library HXPhotoPicker (3.2.1)
  Building ios libraries with archs ["arm64", "armv7"]
  lipo -create -output ios/HXPhotoPicker.framework/Versions/A/HXPhotoPicker build-arm64/libHXPhotoPicker.a
  build-armv7/libHXPhotoPicker.a build-x86_64/libHXPhotoPicker.a
  Copying license
  Copying resources [""]
cp: missing destination file operand after 'ios/HXPhotoPicker.framework/Versions/A/Resources'
Try 'cp --help' for more information.

Building static library HXPhotoPicker (3.2.1)
Compressing bin_HXPhotoPicker_3.2.1 into bin_HXPhotoPicker_3.2.1.zip
          上传二进制文件
         curl http://localhost:8086/frameworks -F "name=AFNetworking" -F "version=4.0.1" -F "annotate=AFNetworking_4.0.1_log" -F "file=@bin-zip/bin_AFNetworking_4.0.1.zip"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3164k  100    48  100 3164k     47  3129k  0:00:01  0:00:01 --:--:-- 3130k

Validating spec
 -> AFNetworking (4.0.1)
    - WARN  | [iOS] vendored_libraries: `*.a` does not match the expected static library name format `lib[name].a`

The repo `mbabin` at `../../../.cocoapods/repos/mbabin` is not clean
          上传二进制文件
         curl http://localhost:8086/frameworks -F "name=HXPhotoPicker" -F "version=3.2.1" -F "annotate=HXPhotoPicker_3.2.1_log" -F "file=@bin-zip/bin_HXPhotoPicker_3.2.1.zip"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26.7M  100    49  100 26.7M     45  24.7M  0:00:01  0:00:01 --:--:-- 24.7M

Validating spec
 -> HXPhotoPicker (3.2.1)
    - WARN  | summary: The summary should be a short version of `description` (max 140 characters).
    - WARN  | description: The description is shorter than the summary.
    - WARN  | [iOS] vendored_libraries: `*.a` does not match the expected static library name format `lib[name].a`

The repo `mbabin` at `../../../.cocoapods/repos/mbabin` is not clean

Updating Spec Repositories

更新私有源仓库 mbabin
更新私有源仓库 mbabinSource

[!] ====== cocoapods-imy-bin 0.3.1.3 版本 ========

[!] ======  dev 环境 ========

[!] ====== archive-white-pod-list = ["loohaBin"]

[!] ====== ignore_git_list = []

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

[!] 【loohaBin | 1】组件spec push失败 .

[!] 【AFNetworking | 4.0.1】组件spec push失败 .

[!] 【HXPhotoPicker | 3.2.1】组件spec push失败 .
  
# **本地服务文件：**
{"HXPhotoPicker":["3.2.1"],"AFNetworking":["4.0.1"]}

**Comment by rbyyy** [comment]
你是不是上传过这些库的podspec到spec仓库中，如果上传过，需要先删除二进制在pod仓库中的podspec.json文件，然后到mongodb中删除相应组件库的记录。最后删除相应的二进制文件zip包。

**Comment by looha518** [comment]
> 你是不是上传过这些库的podspec到spec仓库中，如果上传过，需要先删除二进制在pod仓库中的podspec.json文件，然后到mongodb中删除相应组件库的记录。最后删除相应的二进制文件zip包。

没有上传成功过，仓库中一直都是空的

**Comment by looha518** [comment]
招到原因了，源地址必须使用ssh才能搞定。。。
