### ISSUE TITLE
pod bin auto之后报错

### ISSUE THREAD

**Issue by duzhongjieqiji** [MeetYouDevs/cocoapods-imy-bin#176]
.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/user_interface/error_report.rb:34:in `force_encoding': can't modify frozen String (FrozenError)

**Comment by duzhongjieqiji** [comment]
解决了，自己建的工程，没用demoi

**Comment by Maling1255** [comment]
> 解决了，自己建的工程，没用demo

我自己建的工程，组件二进制制作成功了， 可是在使用二进制（pod bin update --no-repo-update）的时候报了这个错

**Comment by Maling1255** [comment]
> > 解决了，自己建的工程，没用demo
> 
> 我自己建的工程，组件二进制制作成功了， 可是在使用二进制（pod bin update --no-repo-update）的时候报了这个错

我的这个问题也好了， 多执行几次这命令就好了， 不知道咋回事，
