### ISSUE TITLE
pod bin auto 不会生成zip文件，spec push失败

### ISSUE THREAD

**Issue by Jentlezhi** [MeetYouDevs/cocoapods-imy-bin#18]
Building static Library JZToast (0.1.4)
  Building ios libraries with archs ["arm64", "armv7"]
  lipo -create -output ios/JZToast.framework/Versions/A/JZToast
  build-arm64/libJZToast.a build-armv7/libJZToast.a build-x86_64/libJZToast.a
  Writing module map           framework module JZToast {             umbrella
  header "JZToast.h"              export *             module * { export * }
  }
  Copying license
          上传二进制文件
         curl http://localhost:8080/frameworks -F "name=JZToast" -F "version=0.1.4" -F "annotate=JZToast_0.1.4_log" -F "file=@bin-zip/bin_JZToast_0.1.4.zip"

Updating Spec Repositories

更新私有源仓库 gitee-jentle_095-bin_specs
更新私有源仓库 remoteSpec
  $ /usr/bin/git -C /Users/Jentle/.cocoapods/repos/remoteSpec fetch origin
  --progress
  $ /usr/bin/git -C /Users/Jentle/.cocoapods/repos/gitee-jentle_095-bin_specs
  fetch origin --progress
  $ /usr/bin/git -C /Users/Jentle/.cocoapods/repos/gitee-jentle_095-bin_specs
  rev-parse --abbrev-ref HEAD
  $ /usr/bin/git -C /Users/Jentle/.cocoapods/repos/remoteSpec rev-parse
  --abbrev-ref HEAD
  master
  master
  $ /usr/bin/git -C /Users/Jentle/.cocoapods/repos/gitee-jentle_095-bin_specs
  reset --hard origin/master
  $ /usr/bin/git -C /Users/Jentle/.cocoapods/repos/remoteSpec reset --hard
  origin/master
  HEAD is now at 30068a8 [Add] LKDBHelper (2.5.3)
  HEAD is now at d488245 [Update] JZToast (0.1.4)

[!] ====== cocoapods-imy-bin 0.2.9.1 版本 ========

[!] ======  dev 环境 ========

[!] 【JZToast | 0.1.4】组件spec push失败 .

**Comment by Jentlezhi** [comment]
建议搞个交流群，大家一起讨论一下，然后开源，大家一起搞起来可好？

**Comment by su350380433** [comment]
> 建议搞个交流群，大家一起讨论一下，然后开源，大家一起搞起来可好？

咋们这不是开源了吗

**Comment by Jentlezhi** [comment]
组件spec push失败 ，这个其他人也有提过，好像你给关了

**Comment by Jentlezhi** [comment]
合成zip这步失败了，但是也没有具体的原因

**Comment by su350380433** [comment]
> 合成zip这步失败了，但是也没有具体的原因

只有这个失败了？还是所有的都失败了？

**Comment by Jentlezhi** [comment]
方便的话 加个qq指导下？q:1789289135

**Comment by Jentlezhi** [comment]
demo 可以打zip成功，push失败。自己写的，不会生成zip，push失败。

**Comment by su350380433** [comment]
> demo 可以打zip成功，push失败。自己写的，不会生成zip，push失败。

您的静态资源服务有问题

**Comment by GoodLuckerBody** [comment]
> 方便的话 加个qq指导下？q:1789289135

作者都开源让大家使用了，现在的年轻人，还得让人手把手教，把别人当成什么了？这中国的风气真不咋样

**Comment by Jentlezhi** [comment]
> > 方便的话 加个qq指导下？q:1789289135
> 
> 作者都开源让大家使用了，现在的年轻人，还得让人手把手教，把别人当成什么了？这中国的风气真不咋样

你不要站在道德的制高点来谴责这个那个的，有问题就就解决问题，况且没让你解决，你在这愤青什么，闲的吗？

**Comment by Jentlezhi** [comment]
> > > 方便的话 加个qq指导下？q:1789289135
> > 
> > 
> > 作者都开源让大家使用了，现在的年轻人，还得让人手把手教，把别人当成什么了？这中国的风气真不咋样
> 
> 你不要站在道德的制高点来谴责这个那个的，有问题就就解决问题，况且没让你解决，你在这愤青什么，闲的吗？

还什么中国风气不好，你不是中国人？

**Comment by GoodLuckerBody** [comment]
> > > > 方便的话 加个qq指导下？q:1789289135
> > > 
> > > 
> > > 作者都开源让大家使用了，现在的年轻人，还得让人手把手教，把别人当成什么了？这中国的风气真不咋样
> > 
> > 
> > 你不要站在道德的制高点来谴责这个那个的，有问题就就解决问题，况且没让你解决，你在这愤青什么，闲的吗？
> 
> 还什么中国风气不好，你不是中国人？

就因为是中国人，看到你，感到令人伤心。
别人都开源给你用了，好像还欠你的，还得指导、手把手教，这风气真不好

**Comment by Jentlezhi** [comment]
> > > > > 方便的话 加个qq指导下？q:1789289135
> > > > 
> > > > 
> > > > 作者都开源让大家使用了，现在的年轻人，还得让人手把手教，把别人当成什么了？这中国的风气真不咋样
> > > 
> > > 
> > > 你不要站在道德的制高点来谴责这个那个的，有问题就就解决问题，况且没让你解决，你在这愤青什么，闲的吗？
> > 
> > 
> > 还什么中国风气不好，你不是中国人？
> 
> 就因为是中国人，看到你，感到令人伤心。
> 别人都开源给你用了，好像还欠你的，还得指导、手把手教，这风气真不好

我这出现问题了，去问，去寻求解决方法，什么叫手把手教了，什么叫欠我的？你不会说话，请闭嘴，别bb, 我什么地方说作者钱我的了，真是小人~~滚

**Comment by GoodLuckerBody** [comment]
> > > > > > 方便的话 加个qq指导下？q:1789289135
> > > > > 
> > > > > 
> > > > > 作者都开源让大家使用了，现在的年轻人，还得让人手把手教，把别人当成什么了？这中国的风气真不咋样
> > > > 
> > > > 
> > > > 你不要站在道德的制高点来谴责这个那个的，有问题就就解决问题，况且没让你解决，你在这愤青什么，闲的吗？
> > > 
> > > 
> > > 还什么中国风气不好，你不是中国人？
> > 
> > 
> > 就因为是中国人，看到你，感到令人伤心。
> > 别人都开源给你用了，好像还欠你的，还得指导、手把手教，这风气真不好
> 
> 我这出现问题了，去问，去寻求解决方法，什么叫手把手教了，什么叫欠我的？你不会说话，请闭嘴，别bb, 我什么地方说作者钱我的了，真是小人~~滚

请问 这是啥？
> 加个qq指导下？q:1789289135

**Comment by Jentlezhi** [comment]
你就是所谓的键盘侠，没事闲的乱评论，你要是有时间提升下自己该怎么说话，尊重是相互的。明白？

**Comment by GoodLuckerBody** [comment]
> 你就是所谓的键盘侠，没事闲的乱评论，你要是有时间提升下自己该怎么说话，尊重是相互的。明白？

你就是所谓的白飘党，你这个就是互相尊重的意思了！？原来国人是这样互相尊重的吗！？
> 请闭嘴，别bb, 我什么地方说作者钱我的了，真是小人~~滚

**Comment by DengBX** [comment]
> > 方便的话 加个qq指导下？q:1789289135
> 
> 作者都开源让大家使用了，现在的年轻人，还得让人手把手教，把别人当成什么了？这中国的风气真不咋样

那争取滚去你的美国爹那里当狗吧
