### ISSUE TITLE
生成二进制失败，cocopods版本1.9.3

### ISSUE THREAD

**Issue by jasparchan** [MeetYouDevs/cocoapods-imy-bin#19]
Building static framework Demo (1)
  command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  ARCHS='arm64' OTHER_CFLAGS='-fembed-bitcode -Qunused-arguments'
  CONFIGURATION_BUILD_DIR=/Users/robin/Downloads/cocoapods-imy-bin-demo-master/Demo-build-temp/bin-archive/Demo/build-arm64 clean build -configuration Debug -target Demo -project ./Pods/Pods.xcodeproj 2>&1
  command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  ARCHS='armv7' OTHER_CFLAGS='-fembed-bitcode -Qunused-arguments'
  CONFIGURATION_BUILD_DIR=/Users/robin/Downloads/cocoapods-imy-bin-demo-master/Demo-build-temp/bin-archive/Demo/build-armv7 clean build -configuration Debug -target Demo -project ./Pods/Pods.xcodeproj 2>&1
  Building simulator libraries
  command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  -sdk iphonesimulator ARCHS='x86_64'  CONFIGURATION_BUILD_DIR=/Users/robin/Downloads/cocoapods-imy-bin-demo-master/Demo-build-temp/bin-archive/Demo/build-x86_64 clean build
  -configuration Debug -target Demo -project ./Pods/Pods.xcodeproj 2>&1
          上传二进制文件
         curl http://localhost:9090/framework -F "name=Demo" -F "version=1" -F "annotate=Demo_1_log" -F "file=@bin-zip/bin_Demo_1.zip"

Updating Spec Repositories

更新私有源仓库 suvapp_spec_bin_dev
更新私有源仓库 suvapp_spec_source
  $ /usr/bin/git -C /Users/robin/.cocoapods/repos/suvapp_spec_source fetch origin --progress
  $ /usr/bin/git -C /Users/robin/.cocoapods/repos/suvapp_spec_bin_dev fetch origin --progress
  $ /usr/bin/git -C /Users/robin/.cocoapods/repos/suvapp_spec_bin_dev rev-parse --abbrev-ref HEAD
  $ /usr/bin/git -C /Users/robin/.cocoapods/repos/suvapp_spec_source rev-parse --abbrev-ref HEAD
  master
  master
  $ /usr/bin/git -C /Users/robin/.cocoapods/repos/suvapp_spec_bin_dev reset --hard origin/master
  $ /usr/bin/git -C /Users/robin/.cocoapods/repos/suvapp_spec_source reset --hard origin/master
  HEAD is now at 6c7598b init
  HEAD is now at 2b79a34 Add new file

[!] cocoapods-generate requires CocoaPods >= 1.5.0

[!] ====== cocoapods-imy-bin 0.2.9.1 版本 ========

[!] ======  dev 环境 ========

[!] ====== archive-white-pod-list = ["Demo", "YYCache"]

[!] ====== ignore_git_list = ["git@gitlab.xxx.com:Github-iOS"]

[!] 【Demo | 1】组件spec push失败 .

**Comment by su350380433** [comment]
服务器能打开吗，是我的Demo？

http://localhost:9090/framework

**Comment by jasparchan** [comment]
> 服务器能打开吗，是我的Demo？
> 
> http://localhost:9090/framework

robin@robinchandeMacBook-Pro binary-server % npm start

> binary-server@0.1.0 start /Users/robin/suvapps/cocoapods-imy-bin/binary-server
> node app.js

(node:20022) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:20022) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:20022) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/Users/robin/suvapps/cocoapods-imy-bin/binary-server/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:314:20)
    at /Users/robin/suvapps/cocoapods-imy-bin/binary-server/node_modules/mongodb/lib/core/connection/pool.js:562:14
    at /Users/robin/suvapps/cocoapods-imy-bin/binary-server/node_modules/mongodb/lib/core/connection/pool.js:995:11
    at /Users/robin/suvapps/cocoapods-imy-bin/binary-server/node_modules/mongodb/lib/core/connection/connect.js:31:7
    at callback (/Users/robin/suvapps/cocoapods-imy-bin/binary-server/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.<anonymous> (/Users/robin/suvapps/cocoapods-imy-bin/binary-server/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:20022) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20022) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

检查了一下，发生启动服务的时候，连接数据库出错了，数据库已经正常启动

**Comment by jasparchan** [comment]
神奇，换了台机器，就成功了

**Comment by jasparchan** [comment]
换到自己的项目，出现以下错误呢
[!] Unknown configurations whitelisted: debug_debug and prerelease. CocoaPods found debug and release, did you mean one of these?

**Comment by su350380433** [comment]
> 换到自己的项目，出现以下错误呢
> [!] Unknown configurations whitelisted: debug_debug and prerelease. CocoaPods found debug and release, did you mean one of these?

兄弟来点更详细的信息，Pofile 有什么，Binarchive.json是什么

**Comment by jasparchan** [comment]
> > 换到自己的项目，出现以下错误呢
> > [!] Unknown configurations whitelisted: debug_debug and prerelease. CocoaPods found debug and release, did you mean one of these?
> 
> 兄弟来点更详细的信息，Pofile 有什么，Binarchive.json是什么

大佬，这是我这边的信息哈
Binarchive.json 
`{
    "//":"archive-white-pod-list  制作二进制白名单",
    "archive-white-pod-list" : [
        "iYourSuv",
        "CL_ShanYanSDK",
        "PLShortVideoKit",
        "UMCCommon",
        "Bugly",
        "GTSDK",
        "GDTMobSDK",
        "QIYU_iOS_SDK",
        "3DCarPod"
    ],
    "ignore-git-list": [

    ],
    "ignore-http-list": [
        
    ]
}
`

`source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!
plugin 'cocoapods-imy-bin'
use_binaries!

target 'iYourSuv' do
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['VALID_ARCHS'] = 'arm64'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DD_LEGACY_MACROS=1']
      end
    end
  end
  
  #滴滴哆啦A梦组件
  pod 'DoraemonKit/Core', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug','Debug_Debug','PreRelease'] #必选
  pod 'DoraemonKit/WithLogger', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug','Debug_Debug','PreRelease'] #可选
  pod 'DoraemonKit/WithLoad', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug','Debug_Debug','PreRelease'] #可选
  pod 'DoraemonKit/WithMLeaksFinder', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug','Debug_Debug','PreRelease'] #可选
  
  pod 'CL_ShanYanSDK'
...

end
`

**Comment by xgjyjy** [comment]
解决了吗?

**Comment by su350380433** [comment]
> > > 换到自己的项目，出现以下错误呢
> > > [!] Unknown configurations whitelisted: debug_debug and prerelease. CocoaPods found debug and release, did you mean one of these?
> > 
> > 
> > 兄弟来点更详细的信息，Pofile 有什么，Binarchive.json是什么
> 
> 大佬，这是我这边的信息哈
> Binarchive.json
> `{
> "//":"archive-white-pod-list 制作二进制白名单",
> "archive-white-pod-list" : [
> "iYourSuv",
> "CL_ShanYanSDK",
> "PLShortVideoKit",
> "UMCCommon",
> "Bugly",
> "GTSDK",
> "GDTMobSDK",
> "QIYU_iOS_SDK",
> "3DCarPod"
> ],
> "ignore-git-list": [
> 
> ```
> ],
> "ignore-http-list": [
>     
> ]
> ```
> 
> }
> `
> Pofile：
> 
> `source 'https://cdn.cocoapods.org/'
> platform :ios, '10.0'
> use_frameworks!
> inhibit_all_warnings!
> plugin 'cocoapods-imy-bin'
> use_binaries!
> 
> target 'iYourSuv' do
> 
> post_install do |installer|
> installer.pods_project.targets.each do |target|
> target.build_configurations.each do |config|
> config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
> config.build_settings['ENABLE_BITCODE'] = 'NO'
> config.build_settings['VALID_ARCHS'] = 'arm64'
> config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DD_LEGACY_MACROS=1']
> end
> end
> end
> 
> #滴滴哆啦A梦组件
> pod 'DoraemonKit/Core', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug','Debug_Debug','PreRelease'] #必选
> pod 'DoraemonKit/WithLogger', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug','Debug_Debug','PreRelease'] #可选
> pod 'DoraemonKit/WithLoad', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug','Debug_Debug','PreRelease'] #可选
> pod 'DoraemonKit/WithMLeaksFinder', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug','Debug_Debug','PreRelease'] #可选
> 
> pod 'CL_ShanYanSDK'
> ...
> 
> end
> `

这个报错信息看不出是什么
> Unknown configurations whitelisted: debug_debug and prerelease. CocoaPods found debug and release, did you mean one of these?
这个有配置了什么呢？ 像是您自己xcode buildsetting的配置项的问题
