### ISSUE TITLE
pod bin auto --all-make 无法成功

### ISSUE THREAD

**Issue by wuchun4** [MeetYouDevs/cocoapods-imy-bin#191]
CocoaPods : 1.11.2
        Ruby : ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin20]
    RubyGems : 3.2.32
        Host : macOS 11.5.2 (20G95)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /usr/local/Cellar/ruby/3.0.3/lib

### Plugins

```
cocoapods-deintegrate  : 1.0.5
cocoapods-generate     : 1.4.1
cocoapods-imy-bin      : 0.3.0.11
cocoapods-plugins      : 1.0.0
cocoapods-project-hmap : 0.0.5
cocoapods-search       : 1.0.1
cocoapods-trunk        : 1.6.0
cocoapods-try          : 1.2.0


### Error

```
TypeError - no implicit conversion of Array into String
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:711:in `initialize'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:711:in `new'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:711:in `from_file'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize'
/usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
/usr/local/bin/ruby_executable_hooks:24:in `eval'
/usr/local/bin/ruby_executable_hooks:24:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by lirs72379** [comment]
请见谅，这是我的自动回复邮件，您的邮件已收到，谢谢！

**Comment by wuchun4** [comment]
> CocoaPods : 1.11.2 Ruby : ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin20] RubyGems : 3.2.32 Host : macOS 11.5.2 (20G95) Xcode : 13.2.1 (13C100) Git : git version 2.32.0 (Apple Git-132) Ruby lib dir : /usr/local/Cellar/ruby/3.0.3/lib
> 
> ### Plugins
> ```
> cocoapods-deintegrate  : 1.0.5
> cocoapods-generate     : 1.4.1
> cocoapods-imy-bin      : 0.3.0.11
> cocoapods-plugins      : 1.0.0
> cocoapods-project-hmap : 0.0.5
> cocoapods-search       : 1.0.1
> cocoapods-trunk        : 1.6.0
> cocoapods-try          : 1.2.0
> 
> 
> ### Error
> ```
> 
> TypeError - no implicit conversion of Array into String /usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:711:in `initialize' /usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:711:in `new' /usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:711:in `from_file' /usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize' /usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new' /usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse' /usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse' /usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse' /usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run' /usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run' /usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>' /usr/local/bin/pod:23:in `load' /usr/local/bin/pod:23:in `<main>' /usr/local/bin/ruby_executable_hooks:24:in `eval' /usr/local/bin/ruby_executable_hooks:24:in `
> 
> '
> ```
> 
> ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
> 
> [!] Oh no, an error occurred.
> ```

**Comment by HMWDavid** [comment]
> 

怎么处理了？能分享一下吗
