### ISSUE TITLE
Build command failed

### ISSUE THREAD

**Issue by FirstTimes** [MeetYouDevs/cocoapods-imy-bin#2]
RuntimeError - Build command failed: xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  ARCHS='arm64 armv7' OTHER_CFLAGS='-fembed-bitcode -Qunused-arguments' CONFIGURATION_BUILD_DIR=build clean build -configuration Debug -target Demo -project ./Pods.xcodeproj 2>&1
Output:
    Command line invocation:
        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild "GCC_PREPROCESSOR_DEFINITIONS=$(inherited)" "ARCHS=arm64 armv7" "OTHER_CFLAGS=-fembed-bitcode -Qunused-arguments" CONFIGURATION_BUILD_DIR=build clean build -configuration Debug -target Demo -project ./Pods.xcodeproj
    
    Build settings from command line:
        ARCHS = arm64 armv7
        CONFIGURATION_BUILD_DIR = build
        GCC_PREPROCESSOR_DEFINITIONS = $(inherited)
        OTHER_CFLAGS = -fembed-bitcode -Qunused-arguments
    
    xcodebuild: error: './Pods.xcodeproj' does not exist.

执行xcodebuild时，./Pods.xcodeproj路径不存在，是要在什么地方去配置这个路径的吗？

**Comment by su350380433** [comment]
Cocoapod 版本号是多少呢？

**Comment by su350380433** [comment]
cocoapods-generate 支持到1.6，2.0的需要去适配下

**Comment by FirstTimes** [comment]
@su350380433 Cocoapod 版本是使用的1.8.4，最终要使用1.9.1可以支持吗？cocoapods-generate 这边是2.0.0，需要怎样去适配啊
- cocoapods-deintegrate                 : 1.0.4
- cocoapods-disable-podfile-validations : 0.1.1
- cocoapods-generate                    : 2.0.0
- cocoapods-imy-bin                     : 0.2.6
- cocoapods-plugins                     : 1.0.0
- cocoapods-search                      : 1.0.0
- cocoapods-stats                       : 1.1.0
- cocoapods-trunk                       : 1.5.0
- cocoapods-try                         : 1.2.0

**Comment by su350380433** [comment]
cocoapods-generate : 2.0.0 这个问题。
目前已修复，请更新到最新版本 0.2.7
