### ISSUE TITLE
pod bin local没有结果该如何确认问题

### ISSUE THREAD

**Issue by Allen-King** [MeetYouDevs/cocoapods-imy-bin#20]
pod bin local是后台执行吧？命令执行的时候没有报错，但是二进制的podspec仓库和静态资源服务器上都没有相应的资源传上去，该如何定位问题啊，谢谢

**Comment by su350380433** [comment]
请给出更详细的操作步骤下

**Comment by Allen-King** [comment]
额 现在实在本机上跑的，按照你的教程配置了静态资源服务器（测试访问是可以的）和插件初始化的信息，专门建了一个存放二进制podspec文件的仓库，然后将工程编译了一下为了明确缓存路径使用xcodebuild编译的，现在想将所有的pod都二进制化在BinArchive.json的白名单基本配置了所有的pod。执行pod bin local的时候没有报错，但是没有结果。使用你的demo测试（直接使用xcode编译的）也是这样的情况。我觉得应该是我那块操作有问题，但是不知道该如何定位

**Comment by su350380433** [comment]
> 额 现在实在本机上跑的，按照你的教程配置了静态资源服务器（测试访问是可以的）和插件初始化的信息，专门建了一个存放二进制podspec文件的仓库，然后将工程编译了一下为了明确缓存路径使用xcodebuild编译的，现在想将所有的pod都二进制化在BinArchive.json的白名单基本配置了所有的pod。执行pod bin local的时候没有报错，但是没有结果。使用你的demo测试（直接使用xcode编译的）也是这样的情况。我觉得应该是我那块操作有问题，但是不知道该如何定位

您先使用 pod bin auto 测试下吧。local 不一定适合您

**Comment by Allen-King** [comment]
我试一下，谢谢回复！但是现在是想应用在主工程里，主工程只有podfile，而且我们主工程里有一些pod单独跑的时候是有问题的😂

**Comment by su350380433** [comment]
> 我试一下，谢谢回复！但是现在是想应用在主工程里，主工程只有podfile，而且我们主工程里有一些pod单独跑的时候是有问题的😂

pod单独跑的时候是有问题的，这套系统能无缝支持。无视单独的Pod是否有问题。

**Comment by Allen-King** [comment]
嗯 看你的文档现在你这套系统是支持这种形式的pod的。我用pod bin auto测试了一下，应该资源上传那块有问题，还有二进制的podspec文件push也失败了。podspec文件是推送到binary_repo_url这个配置指定的仓库里吧？

**Comment by su350380433** [comment]
> 嗯 看你的文档现在你这套系统是支持这种形式的pod的。我用pod bin auto测试了一下，应该资源上传那块有问题，还有二进制的podspec文件push也失败了。podspec文件是推送到binary_repo_url这个配置指定的仓库里吧？

是的

**Comment by Allen-King** [comment]
使用pod pod bin local 需要目录下有podspec文件才可以吗？
