### ISSUE TITLE
 pod bin auto 错误

### ISSUE THREAD

**Issue by xgjyjy** [MeetYouDevs/cocoapods-imy-bin#21]
xiaogedeMac-mini:YYModel huobanxin$ pod bin auto --all-make
/Users/huobanxin/Desktop/cocoapods-imy-bin-demo/YYModel/Benchmark
/Users/huobanxin/Desktop/cocoapods-imy-bin-demo/YYModel/.codecov.yml
/Users/huobanxin/Desktop/cocoapods-imy-bin-demo/YYModel/LICENSE
/Users/huobanxin/Desktop/cocoapods-imy-bin-demo/YYModel/Framework
/Users/huobanxin/Desktop/cocoapods-imy-bin-demo/YYModel/YYModel
/Users/huobanxin/Desktop/cocoapods-imy-bin-demo/YYModel/0.2.0
/Users/huobanxin/Desktop/cocoapods-imy-bin-demo/YYModel/.travis.yml
/Users/huobanxin/Desktop/cocoapods-imy-bin-demo/YYModel/YYModel.podspec
====== cocoapods-imy-bin 0.2.9.1 版本 ======== 

======  dev 环境 ========

======  dev 环境 ========
[pod gen] Running with `pod gen` configuration {         
  use_podfile: true,         
  use_podfile_plugins: true,         
  podfile_plugins: {},         
  use_lockfile: false,         
  use_lockfile_versions: false,         
  use_libraries: true,         
  generate_multiple_pod_projects: false,         
  incremental_installation: false,         
  gen_directory: /Users/huobanxin/Desktop/cocoapods-imy-bin-demo/YYModel-build-temp/bin-archive,         
  auto_open: false,         
  clean: true,         
  podspec_paths: [#<Pathname:/Users/huobanxin/Desktop/cocoapods-imy-bin-demo/YYModel/YYModel.podspec>, #<Pathname:/Users/huobanxin/Desktop/cocoapods-imy-bin-demo/YYModel/YYModel.podspec>],         
  podspecs: [#<Pod::Specification name="YYModel">, #<Pod::Specification name="YYModel">],         
  sources: ["http://git.zhaoshang800.local/app-ios/binary-specs.git", "http://git.zhaoshang800.local/app-ios/Specs.git", "http://git.zhaoshang800.local/app-ios/binary-specs.git", "http://git.zhaoshang800.local/app-ios/Specs.git", "https://cdn.cocoapods.org"],         
  local_sources: [],         
  repo_update: false,         
  use_default_plugins: false,         
  deterministic_uuids: false,         
  share_schemes_for_development_pods: true,         
  warn_for_multiple_pod_sources: false,         
  use_modular_headers: false }

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod bin auto --all-make
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E266)
       Xcode : 11.6 (11E708)
         Git : git version 2.20.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : binary-specs - git - http://git.zhaoshang800.local/app-ios/binary-specs.git @ bd464c69bb47eb23ec399dd81c461ffcaffda7da

               trunk - CDN - https://cdn.cocoapods.org/
               zhaoshang800-app-ios-specs - git - http://git.zhaoshang800.local/app-ios/Specs.git @ 738e59bd762561a2ec2b74d9bd00b8462087d77d

```

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.0
cocoapods-imy-bin                     : 0.2.9.1
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-trunk                       : 1.4.1
cocoapods-try                         : 1.1.0
```

### Error

```
NoMethodError - undefined method `target_definition_list' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/generate/podfile_generator.rb:357:in `target_definition_list'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/generate/podfile_generator.rb:316:in `supported_swift_versions'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_generator.rb:40:in `block in podfile_for_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/podfile.rb:50:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_generator.rb:26:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_generator.rb:26:in `podfile_for_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/generate/podfile_generator.rb:22:in `block in podfiles_by_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/generate/podfile_generator.rb:21:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/generate/podfile_generator.rb:21:in `podfiles_by_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/command/gen.rb:67:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/archive.rb:166:in `block (2 levels) in generate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_env.rb:22:in `execute_with_use_binaries'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/archive.rb:153:in `block in generate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_env.rb:29:in `execute_with_key'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/native/podfile_env.rb:14:in `execute_with_bin_plugin'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/archive.rb:152:in `generate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/archive.rb:70:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/auto.rb:124:in `run_archive'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.2.9.1/lib/cocoapods-imy-bin/command/bin/auto.rb:53:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60target_definition_list%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: Failed to open TCP connection to api.github.com:443 (Connection refused - connect(2) for "api.github.com" port 443)

[!] ====== cocoapods-imy-bin 0.2.9.1 版本 ======== 
 

[!] ======  dev 环境 ======== 
 
xiaogedeMac-mini:YYModel huobanxin$

**Comment by su350380433** [comment]
这个是我提供的Demo吗？把Podfile和Podfile_local 贴出来看看

**Comment by xgjyjy** [comment]
可以加微信或者钉钉吗? 沟通方便一点, 或者你建个群, 我们在群里讨论
