### ISSUE TITLE
pod bin code 报错

### ISSUE THREAD

**Issue by wuzaozhou** [MeetYouDevs/cocoapods-imy-bin#214]
def self.from_dependency(dependency, podfile_path, can_cache)
       
      from_params(dependency.external_source, dependency, podfile_path, can_cache)
   end

调用ExternalSources 里的from_dependency 时，dependency.external_source 是空的，导致NoMethodError - undefined method `key?' for nil:NilClass，请问要怎么解决？

**Comment by lirs72379** [comment]
请见谅，这是我的自动回复邮件，您的邮件已收到，谢谢！

**Comment by arceushs** [comment]
> def self.from_dependency(dependency, podfile_path, can_cache)
> 
> ```
>   from_params(dependency.external_source, dependency, podfile_path, can_cache)
> ```
> 
> end
> 
> 调用ExternalSources 里的from_dependency 时，dependency.external_source 是空的，导致NoMethodError - undefined method `key?' for nil:NilClass，请问要怎么解决？

https://github.com/MeetYouDevs/cocoapods-imy-bin/issues/213, 可以试试我提的这个方案，最近也在用这个插件
