### ISSUE TITLE
什么时候可以使用use_frameworks! ?

### ISSUE THREAD

**Issue by xgjyjy** [MeetYouDevs/cocoapods-imy-bin#22]
项目OC和Swift混编, 必须要使用use_frameworks! ,求支持啊!

**Comment by li6185377** [comment]
Xcode 9.0 之后就支持 swift静态库拉，  cocoapods 我记得是 1.4.1 之后吧

**Comment by su350380433** [comment]
> Xcode 9.0 之后就支持 swift静态库拉， cocoapods 我记得是 1.4.1 之后吧

是的，xcode已经支持 swift静态库了，项目OC和Swift混编不是必须使用 use_frameworks！的.

**Comment by su350380433** [comment]
OC-Swift 混编这里有个Demo，可以参考下
https://github.com/su350380433/Swift-OC-Demo
