### ISSUE TITLE
sudo gem install cocoapods-imy-bin

### ISSUE THREAD

**Issue by xuxueyong** [MeetYouDevs/cocoapods-imy-bin#24]
ERROR:  Could not find a valid gem 'cocoapods-imy-bin' (>= 0) in any repository
ERROR:  Possible alternatives: cocoapods-imy-bin

**Comment by su350380433** [comment]
> ERROR: Could not find a valid gem 'cocoapods-imy-bin' (>= 0) in any repository
> ERROR: Possible alternatives: cocoapods-imy-bin

再试试，被墙？
