### ISSUE TITLE
如何使用源码私有源

### ISSUE THREAD

**Issue by jasparchan** [MeetYouDevs/cocoapods-imy-bin#28]
源码私有源，是要主动推组件上去的吧，有什么格式要求吗

**Comment by jasparchan** [comment]
> > > 没有
> > 
> > 
> > 可否在你的Demo 增加私有源的例子哈，感谢大佬
> 
> 私有库也是一样的

code_repo_url 应该是索引库吧

**Comment by su350380433** [comment]
> > > > 没有
> > > 
> > > 
> > > 可否在你的Demo 增加私有源的例子哈，感谢大佬
> > 
> > 
> > 私有库也是一样的
> 
> code_repo_url 应该是索引库吧

是的
