### ISSUE TITLE
SystemStackError - stack level too deep

### ISSUE THREAD

**Issue by fengshuo1992** [MeetYouDevs/cocoapods-imy-bin#29]
非常感谢你的这个方法 很想实践一下 但是实践过程中出现了问题  在pod bin auto --all-make的过程中 出现 SystemStackError - stack level too deep 这个问题 希望得到指导

**Comment by su350380433** [comment]
请贴出更多的错误信息

**Comment by fengshuo1992** [comment]
这个解决了小弟解决了 帮我看那个pod bin auto 那个问题吧
