### ISSUE TITLE
Demo | 1】组件spec push失败

### ISSUE THREAD

**Issue by Joachim001** [MeetYouDevs/cocoapods-imy-bin#3]
cocoapods版本1.8.4
在demo下执行pod bin auto --all-make
结果如下：
<img width="523" alt="image" src="https://user-images.githubusercontent.com/44601677/86907159-338def00-c147-11ea-8a46-665507404f69.png">
使用http://localhost:8080/frameworks/查看二进制存储服务为空

**Comment by Joachim001** [comment]
而且在除demo外的pod库下执行pod bin auto --all-make报错如下：
NoMethodError - undefined method `target_definition_list' for nil:NilClass
目前使用遇到这两个问题

**Comment by su350380433** [comment]
target_definition_list，看下Podfile的写法

**Comment by su350380433** [comment]
看了下，您的二进制私有源仓库是这个吗？
https://github.com/Joachim001/example_spec_bin_dev
 这个仓库空了，把CocoaPods-version.yml 文件提交上去再试试

**Comment by Joachim001** [comment]
CocoaPods-version.yml文件已经提交但是还是提示组件push失败...
target_definition_list这个是要改动组件的Podfile么？能说的详细些么 谢谢

**Comment by su350380433** [comment]
你那边可以提供Demo看看？要看下具体的错误才能知道哪里出问题了

**Comment by Joachim001** [comment]
demo的话我就是直接使用的您的项目里的demo 执行的pod bin auto --all-make
我看了下日志好像是制作二进制失败了 下面是日志
Building static Library FMDB (2.7.5)
  Building ios libraries with archs ["arm64", "armv7"]
  libtool -arch_only arm64 -static -o build/package-FMDB-arm64.a
  build-simulator/libFMDB.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no library created (no object files in input files matching -arch_only arm64)
  libtool -arch_only armv7 -static -o build/package-FMDB-armv7.a
  build-simulator/libFMDB.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no library created (no object files in input files matching -arch_only armv7)
  lipo -create -output ios/FMDB.framework/Versions/A/FMDB
  build/package-FMDB-arm64.a build/package-FMDB-armv7.a
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: build/package-FMDB-arm64.a (No such file or directory)
          上传二进制文件
         curl http://localhost:8080/frameworks -F "name=Demo" -F "version=1" -F "annotate=Demo_1_log" -F "file=@bin-zip/bin_Demo_1.zip"
          上传二进制文件
         curl http://localhost:8080/frameworks -F "name=FMDB" -F "version=2.7.5" -F "annotate=FMDB_2.7.5_log" -F "file=@bin-zip/bin_FMDB_2.7.5.zip"

**Comment by su350380433** [comment]
push失败了，看下您本地的服务是否正常呢？
http://localhost:8080/frameworks

**Comment by Joachim001** [comment]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/44601677/87012680-28e16180-c1fc-11ea-99c1-1a0ceef0a8ea.png">
<img width="439" alt="image" src="https://user-images.githubusercontent.com/44601677/87012738-3696e700-c1fc-11ea-9b37-d70089eeb779.png">
服务是这样的 只有一个花括号 刷新不出您视频演示的组件版本号

**Comment by su350380433** [comment]
## 1、有个配置项，您是否有配置过呢
`xx:Demo slj$ pod bin init

======  dev 环境 ========

开始设置二进制化初始信息.
所有的信息都会保存在 /Users/slj/.cocoapods/bin_dev.yml 文件中.
%w[bin_dev.yml bin_debug_iphoneos.yml bin_release_iphoneos.yml] 
你可以在对应目录下手动添加编辑该文件. 文件包含的配置信息样式如下：

---
configuration_env: dev
code_repo_url: git@github.com:su350380433/example_spec_source.git
binary_repo_url: git@github.com:su350380433/example_spec_bin_dev.git
binary_download_url: http://localhost:8080/frameworks/%s/%s/zip
download_file_type: zip


编译环境
可选值：[ dev / debug_iphoneos / release_iphoneos ]
旧值：dev
`
## 2、是否有改成您自己的仓库地址，且是有push权限的
`code_repo_url: git@github.com:su350380433/example_spec_source.git
binary_repo_url: git@github.com:su350380433/example_spec_bin_dev.git
这两个仓库地址是否有改成您自己的仓库，
`

## 3 确认下制作二进制组件是否成功了
路径在 Demo-build-temp/bin-zip

**Comment by su350380433** [comment]
## 4、您可以手动上传下二进制组件的静态库，看是否能成功。
命令：
``` shell
curl http://localhost:8080/frameworks -F "name=Demo" -F "version=1" -F "annotate=Demo_1_log" -F "file=@bin-zip/bin_Demo_1.zip"
```

**Comment by Joachim001** [comment]
<img width="241" alt="image" src="https://user-images.githubusercontent.com/44601677/87017627-cd66a200-c202-11ea-83fa-1c791c7ac64a.png">
pod bin init也是执行了的 源码和二进制仓库地址改成了自己的 是有push权限的 但是二进制组件看样子没有制作成功
没有bin-zip文件 上面的留言我发的那段日志好像显示二进制没有制作成功 我的xcode版本是11.5

**Comment by su350380433** [comment]
> <img alt="image" width="241" src="https://user-images.githubusercontent.com/44601677/87017627-cd66a200-c202-11ea-83fa-1c791c7ac64a.png">
> 
> pod bin init也是执行了的 源码和二进制仓库地址改成了自己的 是有push权限的 但是二进制组件看样子没有制作成功 没有bin-zip文件 上面的留言我发的那段日志好像显示二进制没有制作成功 我的xcode版本是11.5

1、进入 bin-arvhive文件夹，找到工程，跑起来看看，是否能正常运行。
2、更新下demo 代码，再试试看

**Comment by Joachim001** [comment]
更新了demo
可以build successed 运行起来之后显示空白页面 几秒之后闪退回到主屏幕

**Comment by su350380433** [comment]
> 更新了demo
> 可以build successed 运行起来之后显示空白页面 几秒之后闪退回到主屏幕

能push成功吗，Demo本身就没东西的哈。

**Comment by Joachim001** [comment]
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/44601677/87026965-0efd4a00-c20f-11ea-9c74-5a8988932517.png">
push失败 
您看下这error是制作二进制失败了吧  而且我的Demo-build-temp下面没有bin-zip文件夹

**Comment by Joachim001** [comment]
![](https://user-images.githubusercontent.com/44601677/87026965-0efd4a00-c20f-11ea-9c74-5a8988932517.png)
没有成功 感觉制作二进制组件的时候就失败了呢 没有bin-zip这个文件夹

**Comment by su350380433** [comment]
您的cocoapods-generate 应该是2.0.0的版本，有些适配的问题。
更新到最新版 cocoapods-imy-bin V0.2.8

**Comment by Joachim001** [comment]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/44601677/87104029-50cad680-c289-11ea-9456-0319a9b4e31b.png">
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/44601677/87104139-91c2eb00-c289-11ea-87e0-76ee21683237.png">
更新了下 提示信息变了 但是log上还是有那些错误

**Comment by su350380433** [comment]
到bin-archive/demo/pods/YYModel 看下，对应的组件是不是已经自动替换为二进制组件了
再确认下 bin-zip是否有zip文件输出了
![image](https://user-images.githubusercontent.com/7920527/87105312-29760880-c28d-11ea-9aba-06ae55dc548b.png)

**Comment by FirstTimes** [comment]
bin-zip文件夹下有生成framework文件了，但是文件里面没有生成对应的二进制文件，制作.a文件时报错：

Building static Library YYModel (1.0.4)
  Building ios libraries with archs ["arm64", "armv7"]
  libtool -arch_only arm64 -static -o build/package-YYModel-arm64.a
  build-simulator/libYYModel.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no library created (no object files in input files matching -arch_only arm64)
  libtool -arch_only armv7 -static -o build/package-YYModel-armv7.a
  build-simulator/libYYModel.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no library created (no object files in input files matching -arch_only armv7)
  lipo -create -output ios/YYModel.framework/Versions/A/YYModel
  build/package-YYModel-arm64.a build/package-YYModel-armv7.a
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: build/package-YYModel-arm64.a (No such file or directory)
  Writing module map           framework module YYModel {            
  umbrella header "YYModel.h"              export *             module * {
  export * }           }
  Copying license

Building static library YYModel (1.0.4)
framework没有文件：ios/YYModel.framework/Versions/A/YYModel
          上传二进制文件
         curl http://localhost:8080/frameworks -F "name=Demo" -F "version=1" -F "annotate=Demo_1_log" -F "file=@bin-zip/bin_Demo_1.zip"

其他组件也是一样报错，最后组件二进制版本编译失败

[!] 【FMDB | 2.7.5】组件二进制版本编译失败 .

[!] 【LKDBHelper | 2.5.3】组件二进制版本编译失败 .

[!] 【YYModel | 1.0.4】组件二进制版本编译失败 .

[!] 【Demo | 1】组件spec push失败 .

**Comment by Joachim001** [comment]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/44601677/87115254-4a4a5800-c2a5-11ea-962a-9645ee1250b4.png">
![Uploading image.png…]()
对应的组件没有自动替换为二进制组件了
bin-zip也没有zip文件输出

**Comment by su350380433** [comment]
pod bin auto --all-make 漏了个参数 --configuration=Debug
或者更新到最新版cocoapods-imy0-bin  0.2.9

**Comment by Joachim001** [comment]
<img width="460" alt="image" src="https://user-images.githubusercontent.com/44601677/87138844-9ca16e00-c2d1-11ea-8763-4ef0f8e6570e.png">
嗯 demo运行成功了的 但是NoMethodError - undefined method `target_definition_list' for nil:NilClass这个问题的解决方式您能说的具体些么？这个需要改动现有的所有组件库的podfile是么？

**Comment by su350380433** [comment]
> <img alt="image" width="460" src="https://user-images.githubusercontent.com/44601677/87138844-9ca16e00-c2d1-11ea-8763-4ef0f8e6570e.png">
> 
> 嗯 demo运行成功了的 但是NoMethodError - undefined method `target_definition_list' for nil:NilClass这个问题的解决方式您能说的具体些么？这个需要改动现有的所有组件库的podfile是么？

NoMethodError - undefined method `target_definition_list' for nil:NilClass 具体报错的上下文发来看看

**Comment by Joachim001** [comment]
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/44601677/87142433-1a1bad00-c2d7-11ea-9112-e0c58aa1eb28.png">

**Comment by su350380433** [comment]
项目带有swift组件库吗？能否提供Demo？

**Comment by Joachim001** [comment]
我们项目是纯OC的 组件库也全部是OC的 在您的demo里的YYModel下面执行也是会出现一样的问题 您可以看下

**Comment by Joachim001** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/44601677/87144337-2bb28400-c2da-11ea-9278-35b628d650d4.png">
知道问题在哪里了 这是新创建的测试的pod库 podfile默认是在Example里的 
<img width="640" alt="image" src="https://user-images.githubusercontent.com/44601677/87144848-ffe3ce00-c2da-11ea-972e-bca41b6e97e1.png">
把podfile从Example移动到和.podspec文件同一级目录就可以了
嗯 这里需要手动移动下位置

**Comment by Joachim001** [comment]
在组件下执行pod bin auto报组件spec push失败 
执行pod bin auto --all-make组件本身也报spec push失败，但是组件所依赖的组件却能够打二进制成功

**Comment by Joachim001** [comment]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/44601677/87266034-c5ef1380-c4f6-11ea-8baf-58f92de308ee.png">
在podfile_local中加入
plugin 'cocoapods-imy-bin'
use_binaries!
然后执行pod bin init --no-repo-update报错如上

**Comment by FirstTimes** [comment]
[!] Error installing FMDB
[!] /usr/bin/unzip /var/folders/hk/zk7dxc210sb8bv8ky_jn6r240000gn/T/d20200713-43037-q16fea/file.zip -d /var/folders/hk/zk7dxc210sb8bv8ky_jn6r240000gn/T/d20200713-43037-q16fea

Archive:  /var/folders/hk/zk7dxc210sb8bv8ky_jn6r240000gn/T/d20200713-43037-q16fea/file.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/hk/zk7dxc210sb8bv8ky_jn6r240000gn/T/d20200713-43037-q16fea/file.zip or
        /var/folders/hk/zk7dxc210sb8bv8ky_jn6r240000gn/T/d20200713-43037-q16fea/file.zip.zip, and cannot find /var/folders/hk/zk7dxc210sb8bv8ky_jn6r240000gn/T/d20200713-43037-q16fea/file.zip.ZIP, period.

example_spec_bin_dev上有FMDB的binary.podspec.json，再次执行pod bin auto --all-make时，安装FMDB报错

**Comment by su350380433** [comment]
> <img alt="image" width="903" src="https://user-images.githubusercontent.com/44601677/87270203-030cd300-c502-11ea-9405-af96727780e4.png">
> 
> 制作和使用二进制组件已经走通 但是二进制调试pod bin code FMDB报错如上

pod bin code 把 podfile.local发出来看看
也可以先用 --source 指定下路径

**Comment by su350380433** [comment]
> [!] Error installing FMDB
> [!] /usr/bin/unzip /var/folders/hk/zk7dxc210sb8bv8ky_jn6r240000gn/T/d20200713-43037-q16fea/file.zip -d /var/folders/hk/zk7dxc210sb8bv8ky_jn6r240000gn/T/d20200713-43037-q16fea
> 
> Archive: /var/folders/hk/zk7dxc210sb8bv8ky_jn6r240000gn/T/d20200713-43037-q16fea/file.zip
> End-of-central-directory signature not found. Either this file is not
> a zipfile, or it constitutes one disk of a multi-part archive. In the
> latter case the central directory and zipfile comment will be found on
> the last disk(s) of this archive.
> unzip: cannot find zipfile directory in one of /var/folders/hk/zk7dxc210sb8bv8ky_jn6r240000gn/T/d20200713-43037-q16fea/file.zip or
> /var/folders/hk/zk7dxc210sb8bv8ky_jn6r240000gn/T/d20200713-43037-q16fea/file.zip.zip, and cannot find /var/folders/hk/zk7dxc210sb8bv8ky_jn6r240000gn/T/d20200713-43037-q16fea/file.zip.ZIP, period.
> 
> example_spec_bin_dev上有FMDB的binary.podspec.json，再次执行pod bin auto --all-make时，安装FMDB报错

确认下静态资源服务器是否正常了，大概率zip文件上传没成功

**Comment by su350380433** [comment]
> > <img alt="image" width="903" src="https://user-images.githubusercontent.com/44601677/87270203-030cd300-c502-11ea-9405-af96727780e4.png">
> > 制作和使用二进制组件已经走通 但是二进制调试pod bin code FMDB报错如上
> 
> pod bin code 把 podfile.local发出来看看
> 也可以先用 --source 指定下路径

在podfile给FMDB指定个路径，如
  pod 'FMDB', :podspec => 'https://xxx/fmdb/raw/master/FMDB.podspec'
否则FMDB找不到地址去下载源码，如有强需求后续再完善下默认去github拉取，正常情况下仓库都是指向公司内部git的~

**Comment by Joachim001** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/44601677/87294285-176ac300-c536-11ea-9552-bda11404c8da.png">
podfile.local如上
加了--source这个我是这样弄的pod bin code FMDB --source /Users/XXX/Desktop/fmdb，目录指向的是我从git上down下来的代码目录如下：
<img width="770" alt="image" src="https://user-images.githubusercontent.com/44601677/87294569-87794900-c536-11ea-86a1-bd6718d3571b.png">
报错如下：
<img width="312" alt="image" src="https://user-images.githubusercontent.com/44601677/87295402-afb57780-c537-11ea-9bb6-d33d63dc0f75.png">

**Comment by su350380433** [comment]
pod bin code FMDB  --source=/Users/xxx

**Comment by su350380433** [comment]
> <img alt="image" width="640" src="https://user-images.githubusercontent.com/44601677/87294285-176ac300-c536-11ea-9552-bda11404c8da.png">
> 
> podfile.local如上 加了--source这个我是这样弄的pod bin code FMDB --source /Users/XXX/Desktop/fmdb，目录指向的是我从git上down下来的代码目录如下：
> <img alt="image" width="770" src="https://user-images.githubusercontent.com/44601677/87294569-87794900-c536-11ea-86a1-bd6718d3571b.png">
> 
> 报错如下：
> <img alt="image" width="312" src="https://user-images.githubusercontent.com/44601677/87295402-afb57780-c537-11ea-9bb6-d33d63dc0f75.png">

pod bin code FMDB --source=/Users/xxx

**Comment by Joachim001** [comment]
pod bin code FMDB --source=/Users/xxx
如果我的组件依赖另外三个的第三方组件如AFN、YYModel、YYCache等，那么这个命令就要执行四次是吧？加上FMDB本身

**Comment by su350380433** [comment]
> pod bin code FMDB --source=/Users/xxx
> 如果我的组件依赖另外三个的第三方组件如AFN、YYModel、YYCache等，那么这个命令就要执行四次是吧？加上FMDB本身

可以这样写
pod bin code FMDB, AFN,YYModel ,YYCache--source=/Users/xxx，xx，xx

或者执行四次

**Comment by Joachim001** [comment]
现在整个流程都已走通 编译时间从平均的152s到17s 这个工具真的是666
还有一个小问题 开启二进制之后 打算某个库使用源码 但是如下设置并pod bin install/update之后
`set_use_source_pods ['YYModel']`
貌似没有生效呢

**Comment by su350380433** [comment]
> 现在整个流程都已走通 编译时间从平均的152s到17s 这个工具真的是666
> 还有一个小问题 开启二进制之后 打算某个库使用源码 但是如下设置并pod bin install/update之后
> `set_use_source_pods ['YYModel']`
> 貌似没有生效呢

感谢您的使用与肯定
让更多的人来加入我们，让我们一起来交流学习更上一层~

`编译时间从平均的152s到17s` 您这项目太小了，项目越大效果会更好

**Comment by su350380433** [comment]
> > 现在整个流程都已走通 编译时间从平均的152s到17s 这个工具真的是666
> > 还有一个小问题 开启二进制之后 打算某个库使用源码 但是如下设置并pod bin install/update之后
> > `set_use_source_pods ['YYModel']`
> > 貌似没有生效呢
> 
> 感谢您的使用与肯定
> 让更多的人来加入我们，让我们一起来交流学习更上一层~
> 
> `编译时间从平均的152s到17s` 您这项目太小了，项目越大效果会更好

需要看下您Podfile的写法

**Comment by Joachim001** [comment]
`# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
#use_frameworks!


install! 'cocoapods', :deterministic_uuids => false
source 'https://github.com/CocoaPods/Specs.git'
source 'XXX'
target 'XXX' do
  
  pod 'XXX', '= 0.X.X'
  
  target 'XXXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XXXUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
#      puts "===================>target name #{target.name}"
      if target.name == 'Cordova'
        puts "===================>target name #{target.name}"
          target.build_configurations.each do |config|
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','WK_WEB_VIEW_ONLY=1']
#              puts "===================>target build configure #{config.build_settings}"
          end
      end
  end
end`
上面是podfile内容
`plugin 'cocoapods-imy-bin'
use_binaries!

set_use_source_pods ['FMDB']

#需要替换Podfile里面的组件才写到这里
target 'XXX' do

pod 'XXX', :path => './XXX'

end`
上面是podfile_local内容
目前来说还有这一个没走通 如果这个再通的话 对我现在的项目来说简直不要太完美

**Comment by su350380433** [comment]
对其他90%以上的项目都会是很完美的。
 这Podfile 看不懂

**Comment by Joachim001** [comment]
现在完美了/:strong

**Comment by su350380433** [comment]
> 😄 现在完美了

让更多的人来加入我们，让我们一起来交流学习更上一层~

**Comment by Joachim001** [comment]
set_configuration_env('debug_iphoneos')	
这行和设置编译环境是什么关系呢？如果在pod bin init设置了别的如dev，但是在podfile_local设置的是debug_iphoneos那么以什么为准呢？

**Comment by Joachim001** [comment]
执行pod bin init --bin-url=http://xxx/raw/master/bin_release_iphoneos.yml之后，bin_release_iphoneos.yml配置成功
<img width="291" alt="image" src="https://user-images.githubusercontent.com/44601677/87746675-bc7de800-c823-11ea-8819-88e284abcf12.png">
里面内容如下：

> ---
configuration_env: release_iphoneos
code_repo_url: http://xxx/pod-specs.git
binary_repo_url: http://xxx/binary_spec_release_iPhoneos.git
binary_download_url: http://xxx/frameworks/%s/%s/zip
download_file_type: zip
但是执行pod bin auto --all-make的时候，显示我当前还是dev环境
<img width="350" alt="image" src="https://user-images.githubusercontent.com/44601677/87746812-1b436180-c824-11ea-852a-0a61754467d8.png">

**Comment by su350380433** [comment]
> 执行pod bin init --bin-url=[http://xxx/raw/master/bin_release_iphoneos.yml之后，bin_release_iphoneos.yml配置成功](http://xxx/raw/master/bin_release_iphoneos.yml%E4%B9%8B%E5%90%8E%EF%BC%8Cbin_release_iphoneos.yml%E9%85%8D%E7%BD%AE%E6%88%90%E5%8A%9F)
> <img alt="image" width="291" src="https://user-images.githubusercontent.com/44601677/87746675-bc7de800-c823-11ea-8819-88e284abcf12.png">
> 里面内容如下：
> 
> > configuration_env: release_iphoneos
> > code_repo_url: http://xxx/pod-specs.git
> > binary_repo_url: http://xxx/binary_spec_release_iPhoneos.git
> > binary_download_url: http://xxx/frameworks/%s/%s/zip
> > download_file_type: zip
> 
> 但是执行pod bin auto --all-make的时候，显示我当前还是dev环境
> <img alt="image" width="350" src="https://user-images.githubusercontent.com/44601677/87746812-1b436180-c824-11ea-852a-0a61754467d8.png">
> 然后没有去找bin_release_iphoneos.yml里配置的东西，找的是作者默认的dev的配置

pod bin init 只是配置，并不是使用。
使用请在podfile 带上
``` ruby 
  plugin 'cocoapods-imy-bin' 
  set_configuration_env('release_iphoneos')
```
