### ISSUE TITLE
pod bin auto --all-make 总是报这个错误 是哪里做错了吗

### ISSUE THREAD

**Issue by fengshuo1992** [MeetYouDevs/cocoapods-imy-bin#32]
[!] Error installing FMDB
[!] /usr/bin/curl -f -L -o /var/folders/vs/87twpfj520b1msltd5pcq41r0000gn/T/d20200903-91488-1a98m31/file.zip http://192.168.50.150:20480/frameworks/FMDB/2.7.5/zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.9.3 cocoapods-downloader/1.4.0'

**Comment by su350380433** [comment]
http://192.168.50.150:20480/frameworks/FMDB/2.7.5/zip 
查看下这个地址是否存在

**Comment by fengshuo1992** [comment]
这个需要改成我本地的服务器地址吗？没看到能改的地方啊  大哥搞得我都要放弃这么好的方案了 求带小弟一下

**Comment by fengshuo1992** [comment]
打不开 我需要改什么配置？不应该用我本地的地址吗？ 这几天被你这么好的处理方案都要搞放弃了？ 大哥能不能带带小弟  我太难了

**Comment by fengshuo1992** [comment]
大哥 能不能来个联系方式？群也行啊？ 只要大哥在的地方都行啊

**Comment by su350380433** [comment]
http://192.168.50.150:20480/frameworks/
确认下 静态服务器地址能不能用。

**Comment by fengshuo1992** [comment]
我在研究一下 静态服务器吧  太难了 大哥给我点信心吧

**Comment by fengshuo1992** [comment]
http://192.168.50.150:20480/frameworks/FMDB/2.7.5/zip  这个地址一值访问不了 
mongod 也启动  MongoDB starting : pid=966 port=27017 dbpath=/Users/gzlx/data 64-bit    这个地址有需要在哪里配置吗？ 
在app.js里面 mongoose.connect('mongodb://localhost/binary_database') 这个配置  端口号8080 
http://192.168.50.150:20480  这个地址不是本地的ip吗？ 还是每个人的都一样
现在就差这一步了 能给指导一下吗？ 给推荐点这方面的资料也行 网上关于这个的介绍太少了

**Comment by su350380433** [comment]
照着步骤来

**Comment by y2kbug** [comment]
> http://192.168.50.150:20480/frameworks/
> 确认下 静态服务器地址能不能用。

遇到同样的问题，根本没有配置过http://192.168.50.150 IP与端口20480,  查看源码只有静态服务端口只有在app.js设置8080，找不到20480端口设置位置，能否提供下解决思路？

**Comment by BlueSkyInwind** [comment]
> 照着步骤来

你好，我今天接入也遇到这个问题，你这边能提供下帮助吗 ？

**Comment by zealforbeing** [comment]
> 
遇到了相同的问题，http://192.168.50.150:20480 是根据什么生成的，server的代码里没有这个ip和端口

**Comment by fndppx** [comment]
> > 
> 
> 遇到了相同的问题，http://192.168.50.150:20480 是根据什么生成的，server的代码里没有这个ip和端口

最后解决了么
