### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by design1890** [MeetYouDevs/cocoapods-imy-bin#33]
git@github.com: Permission denied (publickey).

我在进行pod bin auto 的时候一直提示我无权限， 我自己本地尝试我的两个远程仓库都是可以正常访问。

**Comment by su350380433** [comment]
百度下 git 怎么加ssh

**Comment by design1890** [comment]
我本地配置多个地址的ssh就会出错，如果我只保留一个ssh就正常

**Comment by su350380433** [comment]
百度下看怎么加就好了
