### ISSUE TITLE
boost-for-react-native 无法构建二进制

### ISSUE THREAD

**Issue by Dx-zuo** [MeetYouDevs/cocoapods-imy-bin#34]
https://github.com/react-native-community/boost-for-react-native

其他组件都可以跑起来, boost-for-react-native 在构建的时候会提示构建失败, 
![image](https://user-images.githubusercontent.com/17236569/92368110-dc49d200-f129-11ea-8eec-58a9573c55b4.png)

使用 Cocoapods-Packager 可以单独构建出 .a 静态库 
救救孩子! 目前是手工导入使用

**Comment by su350380433** [comment]
不要构建了，设置白名单就好

**Comment by Dx-zuo** [comment]
> 不要构建了，设置白名单就好

好奇问下 为什么没有使用 Cocoapods-Packager  来做二进制构建呢? 我在尝试改代码使用 Cocoapods-Packager  进行构建!

**Comment by su350380433** [comment]
cocoapods-imy-bin 底层也是采用更 Cocoapods-Packager 一样的 xcodebuild，我们在上面加了些其他的东西

**Comment by Dx-zuo** [comment]
> cocoapods-imy-bin 底层也是采用更 Cocoapods-Packager 一样的 xcodebuild，我们在上面加了些其他的东西
