### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by design1890** [MeetYouDevs/cocoapods-imy-bin#36]
目前我们测试下来编译速度有提升百分之二十五左右(我们业务代码较大，非组件管理)， 我们目前也会向组件管理方向发展，非常很感谢你们，这个项目使得让我们团队效率提高不少。

还有一个问题咨询一下，不知道现在是否支持纯swift项目或者混编项目。我们目前有一个项目在做swift转型，我在使用过程中发现问题比较多，我也尝试去解决，但是暂时找不到解决方案？我有看的你们在做swift相关的兼容，所以想问一下，目前现有版本有对swift做支持吗？

**Comment by su350380433** [comment]
目前的版本不支持。
swift版本在测试阶段了

**Comment by design1890** [comment]
期待

**Comment by sunqingquan** [comment]
@su350380433 swift项目什么时候能使用，现在项目编译一次要20m+，效率太低了，可否试用一下swift版本的

**Comment by su350380433** [comment]
最近比较忙

**Comment by Decsunshine** [comment]
是否可以大家一起聊一下方案，我们来实现，提交PR也可以的

**Comment by su350380433** [comment]
> @su350380433 swift项目什么时候能使用，现在项目编译一次要20m+，效率太低了，可否试用一下swift版本的

Swift已经支持

**Comment by su350380433** [comment]
Swift 已经支持
