### ISSUE TITLE
无法生成二进制文件，仅demo几个库可以

### ISSUE THREAD

**Issue by Amberler** [MeetYouDevs/cocoapods-imy-bin#38]
**配置文件**：
Podfile
[![](https://pic.downk.cc/item/5f8842fa1cd1bbb86b1588c9.jpg)](https://pic.downk.cc/item/5f8842fa1cd1bbb86b1588c9.jpg)

[![](https://pic.downk.cc/item/5f88438b1cd1bbb86b15c58c.jpg)](https://pic.downk.cc/item/5f88438b1cd1bbb86b15c58c.jpg)

Git仓库是自建的，有读写权限，二进制资源服务器也搭建了，可以正常上传删除二进制库

**问题**：
1.现象非常奇怪，跑的是提供的demo，如果Podfile不添加新的第三方，可以运行，但是不会提交源码(code_repo_url: git@github.com:su350380433/example_spec_source.git 这个仓库没有源码，这个地址是举例的，仓库是本地的)
2.在demo的Podfile添加任何第三方，均不能生成二进制文件
[![](https://pic.downk.cc/item/5f883ffd1cd1bbb86b14410d.jpg)](https://pic.downk.cc/item/5f883ffd1cd1bbb86b14410d.jpg)
3.自己新起demo在测试，也只有示例{"FMDB":["2.7.5"],"LKDBHelper":["2.5.5"],"YYModel":["1.0.4"]}这几个可以。测试了**AFNetworking**，**SVProgressHUD**，**MJRefresh**，**ReactiveObjC**，**Masonry均失败**。

看了下日志，主要没有生成对应的二进制库，才导致后续一系列问题。

bin-zip目录下，也仅仅只有头文件，没有二进制库
[![](https://pic.downk.cc/item/5f8844b91cd1bbb86b164e01.jpg)](https://pic.downk.cc/item/5f8844b91cd1bbb86b164e01.jpg)

/Demo-build-temp/bin-archive/Demo/ios 对应的库 也只有头文件，没有二进制文件
[![](https://pic.downk.cc/item/5f8845391cd1bbb86b168c44.jpg)](https://pic.downk.cc/item/5f8845391cd1bbb86b168c44.jpg)

/Demo-build-temp/bin-archive/Demo 工程可以运行，跑起来一会就自动退到桌面了

另外也安装旧版本0.2.9，测试还是一样问题，电脑也重启了，xcode是11.5

错误日志：
`  
Building static framework Demo (1)
  command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  ARCHS='arm64' OTHER_CFLAGS='-fembed-bitcode
  -Qunused-arguments' CONFIGURATION_BUILD_DIR=build-arm64 clean build -configuration Debug -target Demo -project
  ./Pods.xcodeproj 2>&1
  command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  ARCHS='armv7' OTHER_CFLAGS='-fembed-bitcode
  -Qunused-arguments' CONFIGURATION_BUILD_DIR=build-armv7 clean build -configuration Debug -target Demo -project
  ./Pods.xcodeproj 2>&1
  Building simulator libraries
  command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  -sdk iphonesimulator ARCHS='x86_64'
  CONFIGURATION_BUILD_DIR=build-x86_64 clean build -configuration Debug -target Demo -project ./Pods.xcodeproj 2>&1

Building static framework AFNetworking (4.0.1)

Building static Library AFNetworking (4.0.1)
  **Building ios libraries with archs ["arm64", "armv7"]**
  **lipo -create -output ios/AFNetworking.framework/Versions/A/AFNetworking build-arm64/libAFNetworking.a**
  **build-armv7/libAFNetworking.a build-x86_64/libAFNetworking.a**
**fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: build-arm64/libAFNetworking.a (No such file or directory)**
  Writing module map           framework module AFNetworking {             umbrella header "AFNetworking.h"
  export *             module * { export * }           }
  Copying license

Building static library AFNetworking (4.0.1)
framework没有文件：ios/AFNetworking.framework/Versions/A/AFNetworking

Building static framework FMDB (2.7.5)

Building static Library FMDB (2.7.5)
  Building ios libraries with archs ["arm64", "armv7"]
  lipo -create -output ios/FMDB.framework/Versions/A/FMDB build-arm64/libFMDB.a build-armv7/libFMDB.a
  build-x86_64/libFMDB.a
  Writing module map           framework module FMDB {             umbrella header "FMDB.h"              export *
  module * { export * }           }
  Copying license

Building static library FMDB (2.7.5)
Compressing bin_FMDB_2.7.5 into bin_FMDB_2.7.5.zip
.......省略......
Pushing the `bin_spec_dev' repo

  $ /usr/bin/git -C /Users/cxd/.cocoapods/repos/bin_spec_dev push origin HEAD
  To 192.168.1.177:amber/bin_spec_dev.git
     946f75d..7a2fba9  HEAD -> master
==============  auto_success
FMDB | 2.7.5
LKDBHelper | 2.5.5
YYModel | 1.0.4

Updating Spec Repositories

更新私有源仓库 bin_spec_dev
更新私有源仓库 1-code_spec_source
  $ /usr/bin/git -C /Users/cxd/.cocoapods/repos/bin_spec_dev fetch origin --progress
  $ /usr/bin/git -C /Users/cxd/.cocoapods/repos/1-code_spec_source fetch origin --progress
  $ /usr/bin/git -C /Users/cxd/.cocoapods/repos/bin_spec_dev rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/cxd/.cocoapods/repos/bin_spec_dev reset --hard origin/master
  HEAD is now at 7a2fba9 [Update] YYModel (1.0.4)
  $ /usr/bin/git -C /Users/cxd/.cocoapods/repos/1-code_spec_source rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/cxd/.cocoapods/repos/1-code_spec_source reset --hard origin/master
  HEAD is now at 24359b8 测试推送

[!] ====== cocoapods-imy-bin 0.2.9.1 版本 ========
[!] ======  dev 环境 ========
[!] ====== archive-white-pod-list = ["Demo", "YYCache"]
[!] ====== ignore_git_list = ["git@gitlab.xxx.com:Github-iOS"]
[!] 【AFNetworking | 4.0.1】组件二进制版本编译失败 .
[!] 【Demo | 1】组件spec push失败 .
[!] ===【 FMDB | 2.7.5 】二进制组件制作完成 ！！！
[!] ===【 LKDBHelper | 2.5.5 】二进制组件制作完成 ！！！
[!] ===【 YYModel | 1.0.4 】二进制组件制作完成 ！！！`

**Comment by su350380433** [comment]
把build-arm64 +armv7 +x86_64贴出来看看，可能没生产.a文件

**Comment by su350380433** [comment]
gem list --local 
cocoapods 部分也贴出来看看

**Comment by su350380433** [comment]
cocoapods-generate (1.6.0)
升级到2.0 试试下

**Comment by Amberler** [comment]
> cocoapods-generate (1.6.0)
> 升级到2.0 试试下


*** LOCAL GEMS ***

cocoapods (1.9.3, 1.9.1)
cocoapods-art (1.0.4)
cocoapods-core (1.9.3, 1.9.1)
cocoapods-deintegrate (1.0.4)
cocoapods-disable-podfile-validations (0.1.1)
cocoapods-downloader (1.4.0)
cocoapods-generate (2.0.0)
cocoapods-imy-bin (0.2.9.1)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.4.1)
cocoapods-try (1.1.0)

现在已经升级了，还是没有生成.a文件
这个是生成二进制文件的中间文件，我给你压缩贴上来。
[https://uu.late.run/api/files/onedrive/document/Dem-build-temp.zip](url)
/Dem-build-temp/bin-archive/Demo/ios/Masonry.framework 有生成的framework，但是就没有二进制文件

**Comment by su350380433** [comment]
demo目录下的，podsepc贴出来看看。
podsepc里面的依赖 s.denpency  要添加下对应的第三方库，无依赖的话，xcodebuild是不会编译.a文件的

**Comment by Amberler** [comment]
> demo目录下的，podsepc贴出来看看。
> podsepc里面的依赖 s.denpency 要添加下对应的第三方库，无依赖的话，xcodebuild是不会编译.a文件的

确实是这个问题，s.denpency 添加之后，才会编译，上传。
感谢大佬百忙之中帮忙解决，谢谢老哥

**Comment by Amberler** [comment]
老哥。现在又遇到一个问题了。开发的私有组件依赖的第三方库都可以打包成静态库，并且可以正常上传，但是组件本身并没有打包成二进制上传，进入到temp看了下也没有组件相关的头文件。组件本身可以编译成功，也可以运行。
pod bin auto 输出的日志可以看到有执行编译组件
你提供的demo运行也是同样的效果，所有依赖的第三方都可以编译上传成功，但组件本身就是push失败
![](https://pic.downk.cc/item/5fb24a3bb18d627113c0e273.jpg)
难道只有在宿主工程里面执行`pod bin auto --all-make `，才能编译上传所有的组件吗？

**Comment by su350380433** [comment]
不影响使用的 就先忽略吧。
