### ISSUE TITLE
Podfile和podspec文件一定要在同一个目录下吗？

### ISSUE THREAD

**Issue by Ackerman64** [MeetYouDevs/cocoapods-imy-bin#39]
原生创建私有库 pod lib create的时候，结构是比较固定清晰的。 Example(Demo)文件夹、库源码文件夹、podspec文件是并列。假设某个私有库不依赖任何别的库，pod bin auto失败。 这块如果能兼容调整的话会更友好。

**Comment by su350380433** [comment]
这涉及到 xcodebuild的编译依赖问题，估计有点难

**Comment by su350380433** [comment]
> 原生创建私有库 pod lib create的时候，结构是比较固定清晰的。 Example(Demo)文件夹、库源码文件夹、podspec文件是并列。假设某个私有库不依赖任何别的库，pod bin auto失败。 这块如果能兼容调整的话会更友好。

大家有什么想法，欢迎提PR
