### ISSUE TITLE
静态库AT_comp_dir问题

### ISSUE THREAD

**Issue by zhengstar** [MeetYouDevs/cocoapods-imy-bin#4]
您好，想请教个问题。静态库中AT_comp_dir返回的路径是类似于 /Users/xxxx/Desktop 这种路径。但是xxxx并不是当前mac用户。请问这时候你们是如何处理的？

**Comment by su350380433** [comment]
有权限问题，第一次手动创建下。

**Comment by zhengstar** [comment]
> 有权限问题，第一次手动创建下。

非常感谢

**Comment by wuzaozhou** [comment]
请问下，类似于 /Users/xxxx/Desktop 这种路径 是在什么时候创建的，怎么修改？
