### ISSUE TITLE
请问 pod bin auto 是否对cocoapods 版本有要求呢

### ISSUE THREAD

**Issue by Hflydragon** [MeetYouDevs/cocoapods-imy-bin#40]

**Comment by su350380433** [comment]
兼容性最好的是1.8.x, 1.9,x版本

**Comment by su350380433** [comment]
swift-oc 混编的建议使用1.9.x以后版本

**Comment by Hflydragon** [comment]
目前我运行 pod bin auto 一直失败的，cocoapods 的版本是1.9.3.  
![image](https://user-images.githubusercontent.com/22166173/98346669-43fc9a80-2051-11eb-8854-ced862c57b0f.png) 卡在这步了

**Comment by su350380433** [comment]
需要更多的错误信息，才能帮助到你

**Comment by Hflydragon** [comment]
你好，大神，code_repo_url 源码私有源这个是做什么用的呢？用demo跑一遍发现这个库没有更新

**Comment by cnjsyyb** [comment]
pod bin auto 执行报错，podspec 未生成此文件
<img width="870" alt="截屏2020-11-07 下午3 41 53" src="https://user-images.githubusercontent.com/39656612/98435662-c51a6700-210f-11eb-9255-ba8d2578ddc5.png">
CocoaPods : 1.10.0
Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
RubyGems : 3.0.3
Host : Mac OS X 10.15.6 (19G2021)

**Comment by su350380433** [comment]
提供下更多的信息，太抽象了

**Comment by cnjsyyb** [comment]
> 提供下更多的信息，太抽象了

/Users/t7macos/Desktop/app02/.DS_Store
/Users/t7macos/Desktop/app02/app02.xcworkspace
/Users/t7macos/Desktop/app02/app02
/Users/t7macos/Desktop/app02/Pods
/Users/t7macos/Desktop/app02/Gemfile
/Users/t7macos/Desktop/app02/Gemfile.lock
/Users/t7macos/Desktop/app02/Podfile
/Users/t7macos/Desktop/app02/app02Tests
/Users/t7macos/Desktop/app02/app02.xcodeproj
/Users/t7macos/Desktop/app02/Podfile.lock
/Users/t7macos/Desktop/app02/app02UITests

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod bin auto
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 12.1 (12A7403)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : gitee-example_spec_dev - git - git@gitee.com:ztsyyb/example_spec_dev.git @ 4860ba5fec7f6d46ba407270bc7a732fe6294c97

               gitee-example_spec_source - git - git@gitee.com:ztsyyb/example_spec_source.git @ b12b21ea29bfc610d6e8a281814907c4a3d7a4ac

               master - git - https://github.com/CocoaPods/Specs.git @ ef23dbcec61ab8331dbe53cf38651125685b8ea0

               myPrivateRepo - git - https://gitee.com/ztsyyb/my-repo.git @ faf3a8514e427149718de47fe391655c69742801

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.1
cocoapods-imy-bin                     : 0.3.0.11
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


platform :ios, '9.0'
use_frameworks!
 inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'app02' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app02
  pod 'SDWebImage'
  pod 'SDWebImage/WebP'
  

end
```

### Error

```
TypeError - no implicit conversion of Array into String
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification.rb:705:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification.rb:705:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification.rb:705:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=no+implicit+conversion+of+Array+into+String&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Can't specify same configuration for two pods if one is in abstract_target and the other is inside, in a target
   https://github.com/CocoaPods/CocoaPods/issues/8732 [open] [1 comment]
   07 May 2019

 - pod install abstract_target with plugin cocoapods-binary cause TypeError - no implicit conversion of Array into String
   https://github.com/CocoaPods/CocoaPods/issues/8660 [closed] [3 comments]
   01 Apr 2019

 - TypeError - no implicit conversion of Array into String
   https://github.com/CocoaPods/CocoaPods/issues/7421 [closed] [59 comments]
   24 Feb 2018

and 4 more at:
https://github.com/cocoapods/cocoapods/search?q=no%20implicit%20conversion%20of%20Array%20into%20String&type=Issues&utf8=✓

**Comment by Hflydragon** [comment]
> > 提供下更多的信息，太抽象了
> 
> /Users/t7macos/Desktop/app02/.DS_Store
> /Users/t7macos/Desktop/app02/app02.xcworkspace
> /Users/t7macos/Desktop/app02/app02
> /Users/t7macos/Desktop/app02/Pods
> /Users/t7macos/Desktop/app02/Gemfile
> /Users/t7macos/Desktop/app02/Gemfile.lock
> /Users/t7macos/Desktop/app02/Podfile
> /Users/t7macos/Desktop/app02/app02Tests
> /Users/t7macos/Desktop/app02/app02.xcodeproj
> /Users/t7macos/Desktop/app02/Podfile.lock
> /Users/t7macos/Desktop/app02/app02UITests
> 
> ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
> 
> ### Command
> ```
> /usr/local/bin/pod bin auto
> ```
> 
> ### Report
> * What did you do?
> * What did you expect to happen?
> * What happened instead?
> 
> ### Stack
> ```
>    CocoaPods : 1.10.0
>         Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
>     RubyGems : 3.0.3
>         Host : Mac OS X 10.15.6 (19G2021)
>        Xcode : 12.1 (12A7403)
>          Git : git version 2.24.3 (Apple Git-128)
> Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
> Repositories : gitee-example_spec_dev - git - git@gitee.com:ztsyyb/example_spec_dev.git @ 4860ba5fec7f6d46ba407270bc7a732fe6294c97
> 
>                gitee-example_spec_source - git - git@gitee.com:ztsyyb/example_spec_source.git @ b12b21ea29bfc610d6e8a281814907c4a3d7a4ac
> 
>                master - git - https://github.com/CocoaPods/Specs.git @ ef23dbcec61ab8331dbe53cf38651125685b8ea0
> 
>                myPrivateRepo - git - https://gitee.com/ztsyyb/my-repo.git @ faf3a8514e427149718de47fe391655c69742801
> 
>                trunk - CDN - https://cdn.cocoapods.org/
> ```
> 
> ### Plugins
> ```
> cocoapods-deintegrate                 : 1.0.4
> cocoapods-disable-podfile-validations : 0.1.1
> cocoapods-generate                    : 2.0.1
> cocoapods-imy-bin                     : 0.3.0.11
> cocoapods-plugins                     : 1.0.0
> cocoapods-search                      : 1.0.0
> cocoapods-stats                       : 1.1.0
> cocoapods-trunk                       : 1.5.0
> cocoapods-try                         : 1.2.0
> ```
> 
> ### Podfile
> ```ruby
> # Uncomment the next line to define a global platform for your project
> # platform :ios, '9.0'
> 
> 
> platform :ios, '9.0'
> use_frameworks!
>  inhibit_all_warnings!
> source 'https://github.com/CocoaPods/Specs.git'
> source 'https://github.com/CocoaPods/Specs.git'
> 
> target 'app02' do
>   # Comment the next line if you don't want to use dynamic frameworks
>   use_frameworks!
> 
>   # Pods for app02
>   pod 'SDWebImage'
>   pod 'SDWebImage/WebP'
>   
> 
> end
> ```
> 
> ### Error
> ```
> TypeError - no implicit conversion of Array into String
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification.rb:705:in `initialize'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification.rb:705:in `new'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification.rb:705:in `from_file'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize'
> /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
> /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
> /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
> /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
> /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
> /usr/local/bin/pod:23:in `load'
> /usr/local/bin/pod:23:in `<main>'
> ```
> 
> ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
> 
> [!] Oh no, an error occurred.
> 
> Search for existing GitHub issues similar to yours:
> https://github.com/CocoaPods/CocoaPods/search?q=no+implicit+conversion+of+Array+into+String&type=Issues
> 
> If none exists, create a ticket, with the template displayed above, on:
> https://github.com/CocoaPods/CocoaPods/issues/new
> 
> Be sure to first read the contributing guide for details on how to properly submit a ticket:
> https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
> 
> Don't forget to anonymize any private data!
> 
> Looking for related issues on cocoapods/cocoapods...
> 
> * Can't specify same configuration for two pods if one is in abstract_target and the other is inside, in a target
>   [CocoaPods/CocoaPods#8732](https://github.com/CocoaPods/CocoaPods/issues/8732) [open] [1 comment]
>   07 May 2019
> * pod install abstract_target with plugin cocoapods-binary cause TypeError - no implicit conversion of Array into String
>   [CocoaPods/CocoaPods#8660](https://github.com/CocoaPods/CocoaPods/issues/8660) [closed] [3 comments]
>   01 Apr 2019
> * TypeError - no implicit conversion of Array into String
>   [CocoaPods/CocoaPods#7421](https://github.com/CocoaPods/CocoaPods/issues/7421) [closed] [59 comments]
>   24 Feb 2018
> 
> and 4 more at:
> [https://github.com/cocoapods/cocoapods/search?q=no%20implicit%20conversion%20of%20Array%20into%20String&type=Issues&utf8=✓](https://github.com/cocoapods/cocoapods/search?q=no%20implicit%20conversion%20of%20Array%20into%20String&type=Issues&utf8=%E2%9C%93)
> 纯swift项目

你这个应该是没有给自己的工程创建 podspec

**Comment by su350380433** [comment]
> podspec

大概率是

**Comment by Hflydragon** [comment]
> > podspec
> 
> 大概率是

有交流群吗？主要是不懂ruby语法，盲猜一些命令

**Comment by su350380433** [comment]
> > > podspec
> > 
> > 
> > 大概率是
> 
> 有交流群吗？主要是不懂ruby语法，盲猜一些命令

加wx ：su1231235

**Comment by JLTG2020** [comment]
> > > podspec
> > 
> > 
> > 大概率是
> 
> 有交流群吗？主要是不懂ruby语法，盲猜一些命令

我也遇到了同样的问题，请问解决了吗？
