### ISSUE TITLE
找不到swift

### ISSUE THREAD

**Issue by qwe023X** [MeetYouDevs/cocoapods-imy-bin#41]
主工程是 OC， development pods 的 pod ，OC 使用swift framework ，找不到swift类，请问下 该怎么解决

**Comment by su350380433** [comment]
把具体的错误信息贴出来看看

**Comment by qwe023X** [comment]
Receiver 'CompatibleAnimationView' for class message is a forward declaration
Receiver type 'CompatibleAnimationView' for instance message is a forward declaration
 Unknown type name 'CompatibleAnimation'; did you mean 'CompatibleAnimationView'
和你掘金里面swift二进制化遇到的第二个问题貌似一样

**Comment by su350380433** [comment]
1、一种办法是，把swift文件 抽离成一个独立的pods。这种最方便。
2、规范化 当前pod库的 头文件引发方式、如加上库名前缀
3、另外一种办法，如果硬要混合在一起，需要在在build设置一些参数，到 xcode DerivedData把swift中间文件 xx-Swift.h 引入到 search paths中

**Comment by qwe023X** [comment]
swift的framework单独抽离成独立的pod，pod 库的头文件 引用方式也加上了库名的前缀了，都还是有刚才的问题。

**Comment by su350380433** [comment]
不考虑维护性问题，可以试下第三种办法
