### ISSUE TITLE
组件spec push失败

### ISSUE THREAD

**Issue by devchena** [MeetYouDevs/cocoapods-imy-bin#42]

**Comment by devchena** [comment]
[!] ====== cocoapods-imy-bin 0.3.0.11 版本 ======== 
 

[!] ======  dev 环境 ======== 
 

[!] ====== archive-white-pod-list = ["Demo", "YYCache"]

[!] ====== ignore_git_list = ["git@gitlab.xxx.com:Github-iOS"]

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

[!] 【Demo | 1】组件spec push失败 .

**Comment by su350380433** [comment]
Demo 组件，可以忽略
