### ISSUE TITLE
这个环境有点难搭。。

### ISSUE THREAD

**Issue by xxxIxxxx** [MeetYouDevs/cocoapods-imy-bin#43]
有没有其他方法可以配置呢？
主要是 mongod 这个安装启动遇到了很多错误🤦‍♂️  后面的还没能进行

**Comment by su350380433** [comment]
mongod，额，跟教程的命令一步步来，已经算是详细的了~

**Comment by LDXu** [comment]
@xxxIxxxx  按着教程应该没问题，不涉及到社区版之类呀。或者可以试试docker，我提交了pull requests
