### ISSUE TITLE
工程目录下的podspec写法

### ISSUE THREAD

**Issue by boduoduo** [MeetYouDevs/cocoapods-imy-bin#45]
![image](https://user-images.githubusercontent.com/18454418/98924393-bb2da500-250f-11eb-805a-c871ee6c654f.png)
大佬，我有两个问题想问一哈：
1、工程目录的podspec文件写法，是不是写一下基本信息，然后把podfile里面的依赖库，在podspec里面通过
s.dependency 'xxx'的形式引入进来就可以了。
2、如果目前工程没有组件化，只是pod引入了github上的第三方库，那就只能把第三方库给打包成二进制文件，主工程是不受影响的。development pods里的未发布的组件貌似也不会被打包成二进制文件。

**Comment by su350380433** [comment]
欢迎提PR
