### ISSUE TITLE
pod bin install 失败了 [!] Unable to add a source with url

### ISSUE THREAD

**Issue by TralyFang** [MeetYouDevs/cocoapods-imy-bin#49]
**1. cocoapods-imy-bin 安装插件成功**

`
$ sudo gem install cocoapods-imy-bin

Successfully installed cocoapods-imy-bin-0.3.0.11
Parsing documentation for cocoapods-imy-bin-0.3.0.11
Done installing documentation for cocoapods-imy-bin after 0 seconds
1 gem installed
`

**2. 执行pod bin install 失败**

`
$ pod bin install

====== cocoapods-imy-bin 0.3.0.11 版本 ======== 

======  dev 环境 ========
Cloning spec repo `su350380433` from `git@github.com:su350380433/example_spec_source.git`
[!] Unable to add a source with url `git@github.com:su350380433/example_spec_source.git` named `su350380433`.
You can try adding it manually in `/Users/username/.cocoapods/repos` or via `pod repo add`.
`

**3. Podfile_local 文件内容 就改了 target 名字，其他的都是复制过来的**

`
#target 'Seeyou' do 不同的项目注意修改下Seeyou的值
#:path => '../IMYYQHome',根据实际情况自行修改，与之前在podfile写法一致

 plugin 'cocoapods-imy-bin'
#是否启用二进制插件，想开启把下面这句注释去掉
#use_binaries!

#需要替换Podfile里面的组件才写到这里
#在这里面的所写的组件库依赖，默认切换为【源码】依赖
target 'LuxuryGoods' do
  #本地库引用
    #pod 'IMYYQHome', :path => '../IMYYQHome'

  #覆盖、自定义组件
  #pod 'IMYVendor', :podspec => 'http://覆盖、自定义/'
end
`

**Comment by su350380433** [comment]
按着步骤一步步来，
`git@github.com:su350380433/example_spec_source.git`是Demo用的，最好自己创建一个。

**Comment by chengssir** [comment]
设置了
---
configuration_env: debug_iphoneos
code_repo_url: git@gitee.com:xxxx/xxxx.git
binary_repo_url: git@gitee.com:xxxx/xxxx.git
binary_download_url: https://gitee.com/xxxx/xxxx/tree/master/dev/%s/%s/zip
download_file_type: zip

pod bin install的时候还是报错
Cloning spec repo `su350380433` from `git@github.com:su350380433/example_spec_bin_dev.git`

**Comment by EdwinXiang** [comment]
有解决吗 我也遇到同样的问题
