### ISSUE TITLE
是否支持Swift项目

### ISSUE THREAD

**Issue by manfengjun** [MeetYouDevs/cocoapods-imy-bin#5]

**Comment by su350380433** [comment]
如果是混编的项目，可以通过 BinArchive.json配置文件过滤不想要的Pod组件库，完全无影响。我们公司也有类似的案例在跑。
swift 已经在研发中，近期会推出。

**Comment by manfengjun** [comment]
好的，非常感谢！我的是swift项目，很少的OC代码，打包真的很慢

**Comment by su350380433** [comment]
你们swift项目 用use_frameworks! 吗？

**Comment by manfengjun** [comment]
> 你们swift项目 用use_frameworks! 吗？

使用了
、、、
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => true

use_frameworks!
inhibit_all_warnings!
```

**Comment by su350380433** [comment]
好吧，这两个星期会推出支持swift版本的

**Comment by 347008893** [comment]
坐等swift版本~

**Comment by HolmesZhao** [comment]
> inhibit_all_warnings!

大佬问下, oc swift 混编的工程, 使用generate_multiple_pod_projects 编译的时候很多第三方的 pod 豆包 `'xxx.h' file not found`, 有遇到么?

![image](https://user-images.githubusercontent.com/19728934/153358526-15345880-9971-451c-a856-cec835c14d8f.png)

**Comment by NoGentleMan** [comment]
> > inhibit_all_warnings!
> 
> 大佬问下, oc swift 混编的工程, 使用generate_multiple_pod_projects 编译的时候很多第三方的 pod 豆包 `'xxx.h' file not found`, 有遇到么?
> 
> ![image](https://user-images.githubusercontent.com/19728934/153358526-15345880-9971-451c-a856-cec835c14d8f.png)

请问你最后是怎么解决的呢？

**Comment by lirs72379** [comment]
请见谅，这是我的自动回复邮件，您的邮件已收到，谢谢！
