### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yangzhixin1** [MeetYouDevs/cocoapods-imy-bin#50]
Fetching external sources
-> Fetching podspec for `**Networking` from `../../../mfnetworking/MFNetworking.podspec`
    获取的 podspec 路径为 `../../../**networking/**Networking.podspec`
Resolving dependencies of `CocoaPods.podfile.yaml`
    CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    CDN: trunk Relative path: all_pods_versions_a_7_5.txt exists! Returning local because checking is only perfomed in repo update
    CDN: trunk Relative path: Specs/a/7/5/AFNetworking/4.0.1/AFNetworking.podspec.json exists! Returning local because checking is only
    perfomed in repo update
    CDN: trunk Relative path: all_pods_versions_1_8_1.txt exists! Returning local because checking is only perfomed in repo update
[!] Unable to find a specification for `***_ThirdConfigPod/MFMasonry` depended upon by `MFNetworking`

解析spec 有subspec 还在失败

**Comment by yangzhixin1** [comment]
这种问题应该怎么解决呢

**Comment by su350380433** [comment]
使用了subspec？ 暂不支持，配置下白名单，或者改下写法

**Comment by yangzhixin1** [comment]
白名单 够呛, 所有的库都依赖 三方版本控制库,都是subspec

**Comment by su350380433** [comment]
1、抽取个底层库，把subspec的搬到这个底层库，其他私有库依赖于该底层库。这样影响不大

**Comment by yangzhixin1** [comment]
![Lark20201120-103122](https://user-images.githubusercontent.com/19408829/99750823-04878100-2b1c-11eb-9ea4-0003078aa3f7.png)
![Lark20201120-103226](https://user-images.githubusercontent.com/19408829/99750826-06514480-2b1c-11eb-9d1d-7b124ddca480.png)
![Lark20201120-103436](https://user-images.githubusercontent.com/19408829/99750828-06e9db00-2b1c-11eb-88e0-040ceef93071.png)


还有会对根目录有没有podfile 文件进行强校验, pod 私有库的podfile 文件一般都放在Example 里面

**Comment by su350380433** [comment]
这种场景比较少

**Comment by yangzhixin1** [comment]
pod lib create  XXX 刚试了试 全都是Example 这种文件样式, 好像还是挺多的

**Comment by su350380433** [comment]
正常的项目 一般不会带 example
