### ISSUE TITLE
set_use_source_pods ['YYKit','SDWebImaage'] 不生效

### ISSUE THREAD

**Issue by YaoJuan** [MeetYouDevs/cocoapods-imy-bin#52]
设置了使用源码的依赖依旧还是全部是二进制版本

**Comment by su350380433** [comment]
放到Podfile_local文件试试

**Comment by YaoJuan** [comment]
> 放到Podfile_local文件试试

您好，试了一下，也是无效。use_binaries_with_spec_selector同样的无效。

**Comment by su350380433** [comment]
把对应的二进制私有源仓库的索引删了，在执行 pod cache clean --all。

**Comment by YaoJuan** [comment]
> 把对应的二进制私有源仓库的索引删了，在执行 pod cache clean --all。

这样肯定是可以的，但是这样就相当于不是白名单功能了。而且直接把二进制库给删了。

**Comment by su350380433** [comment]
环境被污染了，看下Podfile的写法
