### ISSUE TITLE
lipo: can't open input file

### ISSUE THREAD

**Issue by shenmuxi** [MeetYouDevs/cocoapods-imy-bin#54]
使用pod lib create PodBinTest创建一个Pod，运行pod bin auto，提示错误：fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: build-arm64/libPodBinTest.a (No such file or directory)
真实的二进制文件在以下目录：PodBinTest-build-temp/bin-archive/PodBinTest/build-arm64/PodBinTest.framework/PodBinTest，所以lipo的入参build-arm64/libPodBinTest.a是不存在的

**Comment by su350380433** [comment]
测试的话，请使用提供的Demo测试
