### ISSUE TITLE
pod bin code 报错

### ISSUE THREAD

**Issue by YaoJuan** [MeetYouDevs/cocoapods-imy-bin#55]
调试源码切换的时候直接执行pod bin code xx库报错
<img width="729" alt="image" src="https://user-images.githubusercontent.com/16183272/100323818-44110a00-3001-11eb-89aa-84b2c5cfc781.png">

执行pod bin code --list 命令行只是单纯输出“加载完成“四个字

**Comment by YaoJuan** [comment]
经过我自己调试发现是库的external_source为空。这是怎么造成的呢

**Comment by su350380433** [comment]
pod bin code 所对应的组件 有指明源码地址？ 如 pod 'xx', podsepc => 'gitxx'

**Comment by ewangke** [comment]
> pod bin code 所对应的组件 有指明源码地址？ 如 pod 'xx', podsepc => 'gitxx'

请问这个在哪个文件指定
