### ISSUE TITLE
demo运行报错

### ISSUE THREAD

**Issue by lizuba** [MeetYouDevs/cocoapods-imy-bin#56]
在demo下运行pod bin auto 最后跑到
Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: Broken pipe
就停了 请问下这是怎么回事
pod version: 1.9.3
xcode: 11.3.1
ruby version: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Comment by zhangzhifangi** [comment]
你这怎么解决的，我也出现你这个问题了

**Comment by zhangzhifangi** [comment]
@lizuba
