### ISSUE TITLE
请问已有组件二进制构建、上传、下载服务的情况下可否使用此插件

### ISSUE THREAD

**Issue by LynahZ** [MeetYouDevs/cocoapods-imy-bin#57]
有看到文档中需要时候mongodb，需要启动二进制的服务，但是我们现在已有之前搭建的对应服务，可以使用静态库进行构建了，如果想通过此插件实现二进制调试，需要怎么操作呢，感谢

**Comment by su350380433** [comment]
可以使用，但是要自己制作podspec和手动上传zip文件，具体命令看文档

**Comment by LynahZ** [comment]
目前我们的podspec文件使用json格式，并且有一台服务器来进行二进制包的存储、上传下载.zip文件的服务了，可否在不使用binary-server服务的情况下使用，我在插件和配置服务的文档下，没有看到对应的说明呢

**Comment by su350380433** [comment]
可以把旧的重新用 cocopods-imy-bin 做一遍。
文档 https://github.com/su350380433/cocoapods-imy-bin-demo
