### ISSUE TITLE
目前我运行 pod bin auto 一直失败的，cocoapods 的版本是1.9.3.

### ISSUE THREAD

**Issue by JLTG2020** [MeetYouDevs/cocoapods-imy-bin#58]
目前我运行 pod bin auto 一直失败的，cocoapods 的版本是1.9.3.  
![image](https://user-images.githubusercontent.com/22166173/98346669-43fc9a80-2051-11eb-8854-ced862c57b0f.png) 卡在这步了

_Originally posted by @Hflydragon in https://github.com/MeetYouDevs/cocoapods-imy-bin/issues/40#issuecomment-722961634_

**Comment by su350380433** [comment]
贴点更多的信息看看。

**Comment by su350380433** [comment]
项目根目录下 有podspec文件？

**Comment by JLTG2020** [comment]
已解决，麻烦了
