### ISSUE TITLE
二进制化 `SDWebImage 5.1.0` 后，切换源码调试报错

### ISSUE THREAD

**Issue by Navimark** [MeetYouDevs/cocoapods-imy-bin#59]
- 环境：
1. 按照要求配置好了静态资源服务器，并且对 `SDWebImage` （5.1.0） 制作了二进制，该二进制在服务器的路径`~/cocoapods-imy-bin-demo/binary-server/.binary/SDWebImage/5.10.0/SDWebImage.framework_5.10.0.zip`
2. Demo 工程的 `Podfile` 如下
    ```ruby
    platform :ios, '9.0'

    plugin 'cocoapods-imy-bin'
    use_binaries!

    target 'TestSDWebImage' do
    # Comment the next line if you don't want to use dynamic frameworks
    # use_frameworks!
    pod 'SDWebImage','5.10.0'
    # Pods for TestSDWebImage
    end

    ```
3. `pod install` 完成，在 Xcode 添加符号断点 `-[UIImageView sd_setImageWithURL:]` ，工程运行时按照预期在断点停住，展示汇编指令界面，目前为止都符合预期。
- 操作：
在工程目录执行`pod bin code SDWebImage`，预期将 `SDWebImage` 由二进制切换成源码，查看断点上下文源码
- 报错：
`pod bin code SDWebImage`命令报错：
```
RuntimeError - 找不到 /Users/user/Desktop/TestBinCode/XcodeTest/TestSDWebImage/Pods/SDWebImage/SDWebImage.framework/libSDWebImage.a
/Users/user/.rvm/gems/ruby-2.5.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/code.rb:69:in `block in add'
/Users/user/.rvm/gems/ruby-2.5.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/code.rb:66:in `each'
/Users/user/.rvm/gems/ruby-2.5.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/code.rb:66:in `add'
/Users/user/.rvm/gems/ruby-2.5.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/code.rb:51:in `run'
/Users/user/.rvm/gems/ruby-2.5.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/user/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Users/user/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.5.0/bin/pod:23:in `load'
/Users/user/.rvm/gems/ruby-2.5.0/bin/pod:23:in `<main>'
/Users/user/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `eval'
/Users/user/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `<main>'
```
- 尝试 Debug：
找到 `code.rb l:69`，发现 `get_lib_path` 函数会拼接一个后缀为 `.a` 的路径，后续在检测到该路径不存在时报错了
- 问题：
个人理解`SDWebImage` 是被打包成了 framework，在 `.framework` 路径下只会有一个同名的二进制文件，不会有`lib#{name}.a`，这里拼接`.a`后缀是不是有问题，还是我的环境配置错误，导致`.a`没有生成呢？请指教！

**Comment by su350380433** [comment]
pod 'SDWebImage','5.10.0'
给这个指定仓库的路径试下。如
pod 'SDWebImage',:podspec=>"xx"

**Comment by Navimark** [comment]
没太懂啥目的，Podfile 里面这个 SDWebImage 已经是指从 Github 拉取的。我反复看了`code.rb`的代码，好像执行`pod bin auto`就会执行到拼接`.a`的语句，就会导致上面的错误，貌似和指定这个仓库路径没有关系吧？Ruby 新手，只看得懂非常基础的流程，如有误解请指教：)

另外我在配置 bin 插件时，没搞懂需要制定源码私有源 `code_repo_url` 的目的，我制作完`SDWebImage`后，这个私有源里面仍然是空白的。是需要提前将被二进制化组件的源码 clone 一份进去吗？

**Comment by su350380433** [comment]
遇到空白的，先清下podfile.lock和pods

**Comment by Navimark** [comment]
> 没太懂啥目的，Podfile 里面这个 SDWebImage 已经是指从 Github 拉取的。我反复看了`code.rb`的代码，好像执行`pod bin auto`就会执行到拼接`.a`的语句，就会导致上面的错误，貌似和指定这个仓库路径没有关系吧？Ruby 新手，只看得懂非常基础的流程，如有误解请指教：)
> 
> 另外我在配置 bin 插件时，没搞懂需要制定源码私有源 `code_repo_url` 的目的，我制作完`SDWebImage`后，这个私有源里面仍然是空白的。是需要提前将被二进制化组件的源码 clone 一份进去吗？

感谢作者解答。我仔细读了仓库的 README 和里面的链接文档，大概明白了 `code_repo_url` 的目的：它用来指定内部不公开的私有库代码，以便能够在源码和二进制之间切换，而对于托管在 GitHub 上的 Repo 来说，可以不用在这个仓库中指定。

至于`SDWebImage`(v: 5.8.0) 在二进制化时为什么被打包成了 `.framework` 而不是`.a`的原因暂时未知。


### 以下是该二进制生成时的详细日志：
```sh
$ pod bin auto                                                                                                                                                       
/Users/user/Desktop/TestBinCode/SDWebImage/WebImage
/Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage_logo.png
/Users/user/Desktop/TestBinCode/SDWebImage/codecov.yml
/Users/user/Desktop/TestBinCode/SDWebImage/LICENSE
/Users/user/Desktop/TestBinCode/SDWebImage/CHANGELOG.md
/Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage_logo_small.png
/Users/user/Desktop/TestBinCode/SDWebImage/Tests
/Users/user/Desktop/TestBinCode/SDWebImage/Docs
/Users/user/Desktop/TestBinCode/SDWebImage/README.md
/Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage.xcworkspace
/Users/user/Desktop/TestBinCode/SDWebImage/Pods
/Users/user/Desktop/TestBinCode/SDWebImage/.gitignore
/Users/user/Desktop/TestBinCode/SDWebImage/SDWebImageMapKit
/Users/user/Desktop/TestBinCode/SDWebImage/Examples
/Users/user/Desktop/TestBinCode/SDWebImage/Configs
/Users/user/Desktop/TestBinCode/SDWebImage/.github
/Users/user/Desktop/TestBinCode/SDWebImage/.gitattributes
/Users/user/Desktop/TestBinCode/SDWebImage/Package.swift
/Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage.xcodeproj
/Users/user/Desktop/TestBinCode/SDWebImage/Podfile
/Users/user/Desktop/TestBinCode/SDWebImage/.git
/Users/user/Desktop/TestBinCode/SDWebImage/.swiftpm
/Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage
/Users/user/Desktop/TestBinCode/SDWebImage/.travis.yml
/Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage.podspec
====== cocoapods-imy-bin 0.3.0.11 版本 ========

======  dev 环境 ========

======  dev 环境 ========
[pod gen] Running with `pod gen` configuration {
  podfile_path: /Users/user/Desktop/TestBinCode/SDWebImage/Podfile,
  podfile: Podfile,
  use_podfile: true,
  use_podfile_plugins: true,
  podfile_plugins: {"cocoapods-imy-bin"=>{}},
  use_lockfile: false,
  use_lockfile_versions: false,
  use_libraries: false,
  generate_multiple_pod_projects: false,
  incremental_installation: false,
  gen_directory: /Users/user/Desktop/TestBinCode/SDWebImage-build-temp/bin-archive,
  auto_open: false,
  clean: true,
  podspec_paths: [#<Pathname:/Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage.podspec>, #<Pathname:/Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage.podspec>],
  podspecs: [#<Pod::Specification name="SDWebImage">, #<Pod::Specification name="SDWebImage">],
  sources: ["git@git.moumentei.com:user/example_spec_bin_dev.git", "git@git.moumentei.com:user/example_spec_source.git", "git@git.moumentei.com:user/example_spec_bin_dev.git", "git@git.moumentei.com:user/example_spec_source.git", "https://cdn.cocoapods.org"],
  local_sources: [],
  repo_update: false,
  use_default_plugins: false,
  deterministic_uuids: false,
  share_schemes_for_development_pods: true,
  warn_for_multiple_pod_sources: false,
  use_modular_headers: false }

Generating SDWebImage in `../SDWebImage-build-temp/bin-archive/SDWebImage`
    Cleaning gen install directory
    Creating stub application
    Writing Podfile

Installing...
更新私有源仓库 example_spec_bin_dev
更新私有源仓库 moumentei-example_spec_source
          $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev fetch origin --progress
          $ /usr/bin/git -C /Users/user/.cocoapods/repos/moumentei-example_spec_source fetch origin --progress
          $ /usr/bin/git -C /Users/user/.cocoapods/repos/moumentei-example_spec_source rev-parse --abbrev-ref HEAD
          master
          $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev rev-parse --abbrev-ref HEAD
          $ /usr/bin/git -C /Users/user/.cocoapods/repos/moumentei-example_spec_source reset --hard origin/master
          master
          HEAD is now at ff306f9 [Add] SVGAPlayer (2.5.6)
          $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev reset --hard origin/master
          HEAD is now at 2a18b36 Update CocoaLumberjack
Installing SDWebImage (5.8.0)

[!] Please close any current Xcode sessions and use `SDWebImage.xcworkspace` for this project from now on.
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

Performing post-installation steps
    Open `../SDWebImage-build-temp/bin-archive/SDWebImage/SDWebImage.xcworkspace` to work on SDWebImage

Building static framework SDWebImage (5.8.0)
  command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  ARCHS='arm64' OTHER_CFLAGS='-fembed-bitcode -Qunused-arguments'
  CONFIGURATION_BUILD_DIR=/Users/user/Desktop/TestBinCode/SDWebImage-build-temp/bin-archive/SDWebImage/build-arm64 clean build -configuration Debug -target
  SDWebImage-iOS -project ./Pods/Pods.xcodeproj 2>&1
  command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  ARCHS='armv7' OTHER_CFLAGS='-fembed-bitcode -Qunused-arguments'
  CONFIGURATION_BUILD_DIR=/Users/user/Desktop/TestBinCode/SDWebImage-build-temp/bin-archive/SDWebImage/build-armv7 clean build -configuration Debug -target
  SDWebImage-iOS -project ./Pods/Pods.xcodeproj 2>&1
  Building simulator libraries
  command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  -sdk iphonesimulator ARCHS='x86_64'
  CONFIGURATION_BUILD_DIR=/Users/user/Desktop/TestBinCode/SDWebImage-build-temp/bin-archive/SDWebImage/build-x86_64 clean build -configuration Debug -target
  SDWebImage-iOS -project ./Pods/Pods.xcodeproj 2>&1

Building framework  SDWebImage (5.8.0)
  Building ios framework with archs ["arm64", "armv7"]
  lipo -create -output ios/SDWebImage.framework/SDWebImage build-arm64/SDWebImage.framework/SDWebImage build-armv7/SDWebImage.framework/SDWebImage
  build-x86_64/SDWebImage.framework/SDWebImage
Compressing SDWebImage.framework into /Users/user/Desktop/TestBinCode/SDWebImage-build-temp/bin-zip/SDWebImage.framework_5.8.0.zip
          上传二进制文件
         curl http://172.16.0.161:8090/frameworks -F "name=SDWebImage" -F "version=5.8.0" -F "annotate=SDWebImage_5.8.0_log" -F "file=@bin-zip/SDWebImage.framework_5.8.0.zip"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  937k  100    46  100  937k    145  2967k --:--:-- --:--:-- --:--:-- 2967k

Validating spec
 -> SDWebImage (5.8.0)

Updating the `example_spec_bin_dev' repo

  $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev pull
  Already up to date.

Adding the spec to the `example_spec_bin_dev' repo

  $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev status --porcelain
 - [No change] SDWebImage (5.8.0)

Pushing the `example_spec_bin_dev' repo

  $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev push origin HEAD
  Everything up-to-date
==============  auto_success
SDWebImage | 5.8.0


Updating Spec Repositories

更新私有源仓库 example_spec_bin_dev
更新私有源仓库 moumentei-example_spec_source
  $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev fetch origin --progress
  $ /usr/bin/git -C /Users/user/.cocoapods/repos/moumentei-example_spec_source fetch origin --progress
  $ /usr/bin/git -C /Users/user/.cocoapods/repos/moumentei-example_spec_source rev-parse --abbrev-ref HEAD
  $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev rev-parse --abbrev-ref HEAD
  master
  master
  $ /usr/bin/git -C /Users/user/.cocoapods/repos/moumentei-example_spec_source reset --hard origin/master
  $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev reset --hard origin/master
  HEAD is now at ff306f9 [Add] SVGAPlayer (2.5.6)
  HEAD is now at 2a18b36 Update CocoaLumberjack

[!] ====== cocoapods-imy-bin 0.3.0.11 版本 ========


[!] ======  dev 环境 ========


[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

[!] ===【 SDWebImage | 5.8.0 】二进制组件制作完成 ！！！
```

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin18]
    RubyGems : 3.0.6
        Host : macOS 11.0.1 (20B29)
       Xcode : 12.2 (12B45b)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/user/.rvm/rubies/ruby-2.5.0/lib
Repositories : aliyun - git - https://github.com/aliyun/aliyun-specs.git @ aef560a28b7e01157139fe26cc169c85680447f4

               alonemonkey - git - https://github.com/AloneMonkey/MonkeyDevSpecs.git @ ed60bc25eb5fd1867144ac606571ecc02c2ca1c6

               bytedance - git - https://github.com/bytedance/cocoapods_sdk_source_repo.git @ c253b0a88e2f1e2447167e014fe6ca61f37c9682

               cocoapods - git - https://github.com/CocoaPods/Specs.git @ 583611266045f865b330fdfb0cecfea89f7560e5

               cocoapods- - CDN - https://cdn.cocoapods.org/
               example_spec_bin_dev - git - git@git.moumentei.com:user/example_spec_bin_dev.git @ 2a18b36ce61510aa0be2da6f133447a76c9d7b4d

               moumentei-example_spec_source - git - git@git.moumentei.com:user/example_spec_source.git @ ff306f9c07f5f80f800ac24ce494347e94f6353d

               remix - git - git@git.moumentei.com:zhangyushan/RemixSpecs.git @ 30ecb86350f00c791dea54ee8575ab4e3740d162

```

### Plugins

```
cocoapods-binary                      : 0.4.4
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.1
cocoapods-imy-bin                     : 0.3.0.11
cocoapods-packager                    : 1.5.0
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
```

**Comment by su350380433** [comment]
生成framework了，Framework还没去适配

**Comment by CY-0227** [comment]
> > 没太懂啥目的，Podfile 里面这个 SDWebImage 已经是指从 Github 拉取的。我反复看了`code.rb`的代码，好像执行`pod bin auto`就会执行到拼接`.a`的语句，就会导致上面的错误，貌似和指定这个仓库路径没有关系吧？Ruby 新手，只看得懂非常基础的流程，如有误解请指教：)
> > 另外我在配置 bin 插件时，没搞懂需要制定源码私有源 `code_repo_url` 的目的，我制作完`SDWebImage`后，这个私有源里面仍然是空白的。是需要提前将被二进制化组件的源码 clone 一份进去吗？
> 
> 感谢作者解答。我仔细读了仓库的 README 和里面的链接文档，大概明白了 `code_repo_url` 的目的：它用来指定内部不公开的私有库代码，以便能够在源码和二进制之间切换，而对于托管在 GitHub 上的 Repo 来说，可以不用在这个仓库中指定。
> 
> 至于`SDWebImage`(v: 5.8.0) 在二进制化时为什么被打包成了 `.framework` 而不是`.a`的原因暂时未知。
> 
> ### 以下是该二进制生成时的详细日志：
> ```shell
> $ pod bin auto                                                                                                                                                       
> /Users/user/Desktop/TestBinCode/SDWebImage/WebImage
> /Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage_logo.png
> /Users/user/Desktop/TestBinCode/SDWebImage/codecov.yml
> /Users/user/Desktop/TestBinCode/SDWebImage/LICENSE
> /Users/user/Desktop/TestBinCode/SDWebImage/CHANGELOG.md
> /Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage_logo_small.png
> /Users/user/Desktop/TestBinCode/SDWebImage/Tests
> /Users/user/Desktop/TestBinCode/SDWebImage/Docs
> /Users/user/Desktop/TestBinCode/SDWebImage/README.md
> /Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage.xcworkspace
> /Users/user/Desktop/TestBinCode/SDWebImage/Pods
> /Users/user/Desktop/TestBinCode/SDWebImage/.gitignore
> /Users/user/Desktop/TestBinCode/SDWebImage/SDWebImageMapKit
> /Users/user/Desktop/TestBinCode/SDWebImage/Examples
> /Users/user/Desktop/TestBinCode/SDWebImage/Configs
> /Users/user/Desktop/TestBinCode/SDWebImage/.github
> /Users/user/Desktop/TestBinCode/SDWebImage/.gitattributes
> /Users/user/Desktop/TestBinCode/SDWebImage/Package.swift
> /Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage.xcodeproj
> /Users/user/Desktop/TestBinCode/SDWebImage/Podfile
> /Users/user/Desktop/TestBinCode/SDWebImage/.git
> /Users/user/Desktop/TestBinCode/SDWebImage/.swiftpm
> /Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage
> /Users/user/Desktop/TestBinCode/SDWebImage/.travis.yml
> /Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage.podspec
> ====== cocoapods-imy-bin 0.3.0.11 版本 ========
> 
> ======  dev 环境 ========
> 
> ======  dev 环境 ========
> [pod gen] Running with `pod gen` configuration {
>   podfile_path: /Users/user/Desktop/TestBinCode/SDWebImage/Podfile,
>   podfile: Podfile,
>   use_podfile: true,
>   use_podfile_plugins: true,
>   podfile_plugins: {"cocoapods-imy-bin"=>{}},
>   use_lockfile: false,
>   use_lockfile_versions: false,
>   use_libraries: false,
>   generate_multiple_pod_projects: false,
>   incremental_installation: false,
>   gen_directory: /Users/user/Desktop/TestBinCode/SDWebImage-build-temp/bin-archive,
>   auto_open: false,
>   clean: true,
>   podspec_paths: [#<Pathname:/Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage.podspec>, #<Pathname:/Users/user/Desktop/TestBinCode/SDWebImage/SDWebImage.podspec>],
>   podspecs: [#<Pod::Specification name="SDWebImage">, #<Pod::Specification name="SDWebImage">],
>   sources: ["git@git.moumentei.com:user/example_spec_bin_dev.git", "git@git.moumentei.com:user/example_spec_source.git", "git@git.moumentei.com:user/example_spec_bin_dev.git", "git@git.moumentei.com:user/example_spec_source.git", "https://cdn.cocoapods.org"],
>   local_sources: [],
>   repo_update: false,
>   use_default_plugins: false,
>   deterministic_uuids: false,
>   share_schemes_for_development_pods: true,
>   warn_for_multiple_pod_sources: false,
>   use_modular_headers: false }
> 
> Generating SDWebImage in `../SDWebImage-build-temp/bin-archive/SDWebImage`
>     Cleaning gen install directory
>     Creating stub application
>     Writing Podfile
> 
> Installing...
> 更新私有源仓库 example_spec_bin_dev
> 更新私有源仓库 moumentei-example_spec_source
>           $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev fetch origin --progress
>           $ /usr/bin/git -C /Users/user/.cocoapods/repos/moumentei-example_spec_source fetch origin --progress
>           $ /usr/bin/git -C /Users/user/.cocoapods/repos/moumentei-example_spec_source rev-parse --abbrev-ref HEAD
>           master
>           $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev rev-parse --abbrev-ref HEAD
>           $ /usr/bin/git -C /Users/user/.cocoapods/repos/moumentei-example_spec_source reset --hard origin/master
>           master
>           HEAD is now at ff306f9 [Add] SVGAPlayer (2.5.6)
>           $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev reset --hard origin/master
>           HEAD is now at 2a18b36 Update CocoaLumberjack
> Installing SDWebImage (5.8.0)
> 
> [!] Please close any current Xcode sessions and use `SDWebImage.xcworkspace` for this project from now on.
> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
> 
> Performing post-installation steps
>     Open `../SDWebImage-build-temp/bin-archive/SDWebImage/SDWebImage.xcworkspace` to work on SDWebImage
> 
> Building static framework SDWebImage (5.8.0)
>   command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  ARCHS='arm64' OTHER_CFLAGS='-fembed-bitcode -Qunused-arguments'
>   CONFIGURATION_BUILD_DIR=/Users/user/Desktop/TestBinCode/SDWebImage-build-temp/bin-archive/SDWebImage/build-arm64 clean build -configuration Debug -target
>   SDWebImage-iOS -project ./Pods/Pods.xcodeproj 2>&1
>   command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  ARCHS='armv7' OTHER_CFLAGS='-fembed-bitcode -Qunused-arguments'
>   CONFIGURATION_BUILD_DIR=/Users/user/Desktop/TestBinCode/SDWebImage-build-temp/bin-archive/SDWebImage/build-armv7 clean build -configuration Debug -target
>   SDWebImage-iOS -project ./Pods/Pods.xcodeproj 2>&1
>   Building simulator libraries
>   command = xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$(inherited)'  -sdk iphonesimulator ARCHS='x86_64'
>   CONFIGURATION_BUILD_DIR=/Users/user/Desktop/TestBinCode/SDWebImage-build-temp/bin-archive/SDWebImage/build-x86_64 clean build -configuration Debug -target
>   SDWebImage-iOS -project ./Pods/Pods.xcodeproj 2>&1
> 
> Building framework  SDWebImage (5.8.0)
>   Building ios framework with archs ["arm64", "armv7"]
>   lipo -create -output ios/SDWebImage.framework/SDWebImage build-arm64/SDWebImage.framework/SDWebImage build-armv7/SDWebImage.framework/SDWebImage
>   build-x86_64/SDWebImage.framework/SDWebImage
> Compressing SDWebImage.framework into /Users/user/Desktop/TestBinCode/SDWebImage-build-temp/bin-zip/SDWebImage.framework_5.8.0.zip
>           上传二进制文件
>          curl http://172.16.0.161:8090/frameworks -F "name=SDWebImage" -F "version=5.8.0" -F "annotate=SDWebImage_5.8.0_log" -F "file=@bin-zip/SDWebImage.framework_5.8.0.zip"
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  937k  100    46  100  937k    145  2967k --:--:-- --:--:-- --:--:-- 2967k
> 
> Validating spec
>  -> SDWebImage (5.8.0)
> 
> Updating the `example_spec_bin_dev' repo
> 
>   $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev pull
>   Already up to date.
> 
> Adding the spec to the `example_spec_bin_dev' repo
> 
>   $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev status --porcelain
>  - [No change] SDWebImage (5.8.0)
> 
> Pushing the `example_spec_bin_dev' repo
> 
>   $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev push origin HEAD
>   Everything up-to-date
> ==============  auto_success
> SDWebImage | 5.8.0
> 
> 
> Updating Spec Repositories
> 
> 更新私有源仓库 example_spec_bin_dev
> 更新私有源仓库 moumentei-example_spec_source
>   $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev fetch origin --progress
>   $ /usr/bin/git -C /Users/user/.cocoapods/repos/moumentei-example_spec_source fetch origin --progress
>   $ /usr/bin/git -C /Users/user/.cocoapods/repos/moumentei-example_spec_source rev-parse --abbrev-ref HEAD
>   $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev rev-parse --abbrev-ref HEAD
>   master
>   master
>   $ /usr/bin/git -C /Users/user/.cocoapods/repos/moumentei-example_spec_source reset --hard origin/master
>   $ /usr/bin/git -C /Users/user/.cocoapods/repos/example_spec_bin_dev reset --hard origin/master
>   HEAD is now at ff306f9 [Add] SVGAPlayer (2.5.6)
>   HEAD is now at 2a18b36 Update CocoaLumberjack
> 
> [!] ====== cocoapods-imy-bin 0.3.0.11 版本 ========
> 
> 
> [!] ======  dev 环境 ========
> 
> 
> [!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.
> 
> [!] ===【 SDWebImage | 5.8.0 】二进制组件制作完成 ！！！
> ```
> 
> ### Stack
> ```
>    CocoaPods : 1.10.0
>         Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin18]
>     RubyGems : 3.0.6
>         Host : macOS 11.0.1 (20B29)
>        Xcode : 12.2 (12B45b)
>          Git : git version 2.24.3 (Apple Git-128)
> Ruby lib dir : /Users/user/.rvm/rubies/ruby-2.5.0/lib
> Repositories : aliyun - git - https://github.com/aliyun/aliyun-specs.git @ aef560a28b7e01157139fe26cc169c85680447f4
> 
>                alonemonkey - git - https://github.com/AloneMonkey/MonkeyDevSpecs.git @ ed60bc25eb5fd1867144ac606571ecc02c2ca1c6
> 
>                bytedance - git - https://github.com/bytedance/cocoapods_sdk_source_repo.git @ c253b0a88e2f1e2447167e014fe6ca61f37c9682
> 
>                cocoapods - git - https://github.com/CocoaPods/Specs.git @ 583611266045f865b330fdfb0cecfea89f7560e5
> 
>                cocoapods- - CDN - https://cdn.cocoapods.org/
>                example_spec_bin_dev - git - git@git.moumentei.com:user/example_spec_bin_dev.git @ 2a18b36ce61510aa0be2da6f133447a76c9d7b4d
> 
>                moumentei-example_spec_source - git - git@git.moumentei.com:user/example_spec_source.git @ ff306f9c07f5f80f800ac24ce494347e94f6353d
> 
>                remix - git - git@git.moumentei.com:zhangyushan/RemixSpecs.git @ 30ecb86350f00c791dea54ee8575ab4e3740d162
> ```
> 
> ### Plugins
> ```
> cocoapods-binary                      : 0.4.4
> cocoapods-deintegrate                 : 1.0.4
> cocoapods-disable-podfile-validations : 0.1.1
> cocoapods-generate                    : 2.0.1
> cocoapods-imy-bin                     : 0.3.0.11
> cocoapods-packager                    : 1.5.0
> cocoapods-plugins                     : 1.0.0
> cocoapods-search                      : 1.0.0
> cocoapods-stats                       : 1.1.0
> cocoapods-trunk                       : 1.5.0
> cocoapods-try                         : 1.2.0
> ```

你好，请教下code_repo_url具体使用方法，目前制作成功后都是空，谢谢。qq273962965
