### ISSUE TITLE
’pod bin auto‘ 

### ISSUE THREAD

**Issue by lvchenqiang** [MeetYouDevs/cocoapods-imy-bin#60]
本地环境:

pod version: 1.10.0
gem version: 3.0.8
xcode version:  12.2

问题:

在pod库目录中执行 `pod bin auto ` 时, 报错   **exception === copy_headers ./Pods/Headers/Public/YYModel no exist 。**

看起来是 archive.rb中  generate_project 调用 `pod gen ....` 之后,没有生成对应的header文件. 想请问一下,你那边是可以正常生成的嘛？

相关位置的代码:
![image](https://user-images.githubusercontent.com/25682810/102171514-ae66ed00-3ed1-11eb-989f-04b13ff8410e.png)

生成的目录:

![image](https://user-images.githubusercontent.com/25682810/102171752-377e2400-3ed2-11eb-946d-03729f0dd8ab.png)

**Comment by su350380433** [comment]
我们是正常的。
图裂开了，看不了

**Comment by lvchenqiang** [comment]
> 我们是正常的。
> 图裂开了，看不了

图片的内容主要是:

本地在执行 `pod bin auto` 之后没有生成对应的headers文件.   bin-archive/YYModel/Pods/Headers 里面为空。
方便问一下,你们本地的环境配置嘛？
之前没写过ruby , 想问一下 这个Headers文件的生成, 是通过 `pod gen ...`命令嘛, 有什么特殊的参数标识嘛

**Comment by su350380433** [comment]
看下官方文档说明
