### ISSUE TITLE
大佬,有稍微详细一点的教程吗,小白表示很想试用一下,但是遇到各种问题

### ISSUE THREAD

**Issue by yaoboy-ios** [MeetYouDevs/cocoapods-imy-bin#61]
我访问 http://localhost:8080/frameworks/ 这个地址已经可以看到  {"SDWebImage": ["5.10.0"],} 这个结果了，这算是二进制化成功了吗？然后我在项目根目录下配置了Podfile_local 文件
plugin 'cocoapods-imy-bin'
use_binaries!
target "zhangzhi_new" do
pod 'SDWebImage','5.10.0'
end
这个配置对着吗？
然后我执行  pod bin install
![image](https://user-images.githubusercontent.com/15992839/102465582-c7fe6500-4088-11eb-9724-ce5452c2068f.png)
这是什么情况呢。
code_repo_url: 这个地址里面也一直是空白的

**Comment by su350380433** [comment]
可以看下问答和issue
