### ISSUE TITLE
spec中使用了vendored_frameworks的组件无法生成二进制

### ISSUE THREAD

**Issue by huainanzi** [MeetYouDevs/cocoapods-imy-bin#65]
提示：带有 vendored_frameworks 字段，请检查是否有效！！！
源码中看是就直接过滤了
![截屏2020-12-29 上午10 53 38](https://user-images.githubusercontent.com/17873544/103255402-29490100-49c4-11eb-8285-920d666adb68.png)

请教如何解决？

**Comment by jiabibi888** [comment]
> 提示：带有 vendored_frameworks 字段，请检查是否有效！！！ 源码中看是就直接过滤了 ![截屏2020-12-29 上午10 53 38](https://user-images.githubusercontent.com/17873544/103255402-29490100-49c4-11eb-8285-920d666adb68.png)
> 
> 请教如何解决？

你是怎么解决的
