### ISSUE TITLE
端口被占用更改yml文件无效

### ISSUE THREAD

**Issue by SunWuDong** [MeetYouDevs/cocoapods-imy-bin#67]
8080端口被占用了 ,yml文件中的binary_download_url 已经改成8081 , 本地服务器监听也改为8081

执行pod bin install 的时候报错还是8080端口

`[!] /usr/bin/curl -f -L -o /var/folders/hk/1nnwbpc12f92q594mzh0h_p00000gn/T/d20201231-21394-o8g2uw/file.zip http://localhost:8080/frameworks/AFNetworking/3.2.1/zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'`

还有什么位置端口需要改么?

**Comment by su350380433** [comment]
服务也要同时改

**Comment by SunWuDong** [comment]
> 服务也要同时改

是binary-server么? listen已经改过了, 还有什么服务要改?

**Comment by ewangke** [comment]
@SunWuDong 您看下 binary podspec 是不是之前使用 8080 配置时生成的？是的话需要手动改下，或者重新生成

**Comment by SunWuDong** [comment]
> @SunWuDong 您看下 binary podspec 是不是之前使用 8080 配置时生成的？是的话需要手动改下，或者重新生成

我也发现了, 生成索引的时候用的是8080, 要重新生成了

**Comment by JeansHuang** [comment]
你说的yml文件是哪个？在哪?

**Comment by CY-0227** [comment]
> > @SunWuDong 您看下 binary podspec 是不是之前使用 8080 配置时生成的？是的话需要手动改下，或者重新生成
> 
> 我也发现了, 生成索引的时候用的是8080, 要重新生成了

请问这个索引生成是什么
