### ISSUE TITLE
NameError - undefined method `podfile_for_spec' for class `Pod::Generate::PodfileGenerator'

### ISSUE THREAD

**Issue by dabing1022** [MeetYouDevs/cocoapods-imy-bin#68]
看了下，`cocoapods-generate`库从2.1.0版本将 `Pod::Generate::PodfileGenerator`中的方法`podfile_for_spec`修改成了`podfile_for_specs`

建议这里做下版本兼容。

git diff：https://github.com/square/cocoapods-generate/compare/v2.0.1...v2.1.0

**Comment by dabing1022** [comment]
或者强制使用 cocoapods-generate 2.0.1 版本

**Comment by su350380433** [comment]
> 或者强制使用 cocoapods-generate 2.0.1 版本

666
