### ISSUE TITLE
Demo 无法初始化

### ISSUE THREAD

**Issue by miroda** [MeetYouDevs/cocoapods-imy-bin#78]
<img width="1145" alt="企业微信20210111-165626@2x" src="https://user-images.githubusercontent.com/2841126/104161664-33401a80-542e-11eb-97d0-b51e088cbf2c.png">

**Comment by miroda** [comment]
Demo中输入pod bin init 直接报错

**Comment by dabing1022** [comment]
参考这个解决方案：#68

**Comment by miroda** [comment]
already fixed
