### ISSUE TITLE
pod bin auto -> TypeError - no implicit conversion of Array into String

### ISSUE THREAD

**Issue by miroda** [MeetYouDevs/cocoapods-imy-bin#79]
TypeError - no implicit conversion of Array into String
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `initialize'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `new'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `from_file'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users//.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users//.rvm/rubies/ruby-2.6.0/bin/pod:23:in `load'
/Users//.rvm/rubies/ruby-2.6.0/bin/pod:23:in `<main>'
/Users//.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
/Users//.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'

**Comment by miroda** [comment]
Podfile

`#plugin 'cocoapods-imy-bin'
#use_binaries!

#需要替换Podfile里面的组件才写到这里
target 'CCBin' do
pod 'FMDB', :path => '../FMDB'
end

`
Podfile_local
`#需要替换Podfile里面的组件才写到这里
target 'CCBin' do
pod 'FMDB', :path => '../FMDB'
end
`

**Comment by miroda** [comment]
![Uploading 企业微信20210111-180952@2x.png…]()

**Comment by miroda** [comment]
<img width="1151" alt="企业微信20210111-180952@2x" src="https://user-images.githubusercontent.com/2841126/104168052-58d22180-5438-11eb-83da-b48a81b8742d.png">

**Comment by dabing1022** [comment]
可以提供下`pod bin auto`执行的文件夹里的内容截图看看

**Comment by miroda** [comment]
### Command

```
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/bin/pod bin auto
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin19]
    RubyGems : 3.0.8
        Host : macOS 11.1 (20C69)
       Xcode : 12.2 (12B45b)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/hupengfei/.rvm/rubies/ruby-2.6.0/lib
Repositories : aixuexi-axx-app-rd-gsbaselib-ios - git - http://gitlab.ops.aixuexi.com/axx-app-rd/gsbaselib-ios.git @ 3ae6c2087c6daa2a87ec71a95535d4a602c9b645

               aixuexi-axx_tol_spec_bin - git - git@gitlab.ops.aixuexi.com:lol/lol-app-ios/axx_tol_spec_bin.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD

               aixuexi-ccbin - git - git@gitlab.ops.aixuexi.com:hupengfei/ccbin.git @ d64caeda2c25f3af257af8ca27a473f0a43971b5

               aixuexi-gsl-ios-gslsaasspec - git - http://gitlab.ops.aixuexi.com/gsl/ios/gslsaasspec.git @ 167d15a514d76071841a79148205a89a2c894b99

               aixuexi-lol-lol-app-ios-axx_tol_spec_bin - git - http://gitlab.ops.aixuexi.com/lol/lol-app-ios/axx_tol_spec_bin.git @ 096f219a79df3c06a8b121059fff89caa46a1031

               aliyun - git - https://github.com/aliyun/aliyun-specs.git @ d47c1a31a2106ed0dc675a81e9cc2ce83abd9937

               master - git - https://github.com/CocoaPods/Specs.git @ 0c82a2f67b55d0a2098b6432c532cac591d02c95

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.1
cocoapods-imy-bin                     : 0.3.0.11
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#命令写在这里也是等效， 已移动到Podfile_local中，避免git提交冲突等场景
plugin 'cocoapods-imy-bin'
use_binaries!

target 'CCBin' do
  pod 'FMDB'
  # pod 'FMDB',:podspec => 'https://github.com/ccgus/fmdb/blob/master/FMDB.podspec'

end
```

### Error

```
TypeError - no implicit conversion of Array into String
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `initialize'
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `new'
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `from_file'
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize'
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/bin/pod:23:in `load'
/Users/hupengfei/.rvm/rubies/ruby-2.6.0/bin/pod:23:in `<main>'
/Users/hupengfei/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
/Users/hupengfei/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by miroda** [comment]
<img width="209" alt="企业微信20210111-182136@2x" src="https://user-images.githubusercontent.com/2841126/104169016-dcd8d900-5439-11eb-818d-db100fd42bb0.png">

**Comment by dabing1022** [comment]
你这不对呀。作者这个项目的目前的设计，必须要求Podfile、Podspec在同一个目录。你这个缺少Podspec，建议你把作者的 demo 项目跑起来看看。git 地址：	https://github.com/su350380433/cocoapods-imy-bin-demo.git

imy-bin设计思路，使用一个壳工程target，名称随意，在 podspec 中描述后要打包的库，使用 dependency 的形式进行依赖，如果想特别指定 dependency 的branch或者tag或者commit等信息，可以借助 Podfile、Podfile_local 等来辅助。

**Comment by miroda** [comment]
可以了，加上Podspec之后就好了
