### ISSUE TITLE
在用pod bin auto的时候报错

### ISSUE THREAD

**Issue by YaoJuan** [MeetYouDevs/cocoapods-imy-bin#8]
NoMethodError - undefined method `target_definition_list' for nil:NilClass
/Users/bryce/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-generate-2.0.0/lib/cocoapods/generate/podfile_generator.rb:357:in `target_definition_list'

但是我进去找是有这个方法的，请问有遇到过吗？我只是在我自己的项目里用了pod bin auto就出现了这个错误

**Comment by su350380433** [comment]
#3 参考下这个

**Comment by YaoJuan** [comment]
> #3 参考下这个

非常感谢您活跃的回复，看了这个我的确解决了一些问题。初始化了二进制仓库的version文件后的确demo可以跑了。然后在issue3里podfile从Example移动到和.podspec文件同一级目录之后也不会报undefined method的错误了。但是还有2个问题需要请教一下
1.这个文件移动是不是有一些不妥，因为创建一个pod库他的文本目录本来就是之前的结构
2.我在执行pod bin auto的时候上传二进制并没有成功，本地也没有发现.zip包。但是之前的demo是有上传成功的。错误如图，非常感谢回复。同样我也期待您可以建一个交流群。
![image](https://user-images.githubusercontent.com/16183272/87643266-34dd9e00-c77d-11ea-9ed1-ff04d2153eb5.png)

**Comment by su350380433** [comment]
对着Demo看下看少了什么，podspec少了 s.denpendy 
参照 #6

**Comment by YaoJuan** [comment]
> 对着Demo看下看少了什么，podspec少了 s.denpendy
> 参照 #6

您好，我看了一下，我是任何东西都不少的。因为我这个demo是很赶紧的demo，就是新建了2个干净的类。继承nsobject的，我的temp文件夹里只有bin-archive的包，而且没有具体报错，请问这是什么原因呢

**Comment by su350380433** [comment]
![image](https://user-images.githubusercontent.com/7920527/87649329-c00d6280-c782-11ea-9e77-73516c62fe6c.png)
这里少了
命令用的是 `pod bin auto --all-make`

**Comment by YaoJuan** [comment]
> ![image](https://user-images.githubusercontent.com/7920527/87649329-c00d6280-c782-11ea-9e77-73516c62fe6c.png)
> 这里少了
> 命令用的是 `pod bin auto --all-make`
命令我用的是pod bin auot --all-make。但是我这个库不依赖afn，也没有倒入afn，这只是创建私有库的一个模版

**Comment by su350380433** [comment]
> > ![image](https://user-images.githubusercontent.com/7920527/87649329-c00d6280-c782-11ea-9e77-73516c62fe6c.png)
> > 这里少了
> > 命令用的是 `pod bin auto --all-make`
> > 命令我用的是pod bin auot --all-make。但是我这个库不依赖afn，也没有倒入afn，这只是创建私有库的一个模版

依赖什么库，这里要加上

**Comment by YaoJuan** [comment]
> > > ![image](https://user-images.githubusercontent.com/7920527/87649329-c00d6280-c782-11ea-9e77-73516c62fe6c.png)
> > > 这里少了
> > > 命令用的是 `pod bin auto --all-make`
> > > 命令我用的是pod bin auot --all-make。但是我这个库不依赖afn，也没有倒入afn，这只是创建私有库的一个模版
> 
> 依赖什么库，这里要加上

系统库uikit也要吗？里面只是很简单的person类

**Comment by su350380433** [comment]
> > > > ![image](https://user-images.githubusercontent.com/7920527/87649329-c00d6280-c782-11ea-9e77-73516c62fe6c.png)
> > > > 这里少了
> > > > 命令用的是 `pod bin auto --all-make`
> > > > 命令我用的是pod bin auot --all-make。但是我这个库不依赖afn，也没有倒入afn，这只是创建私有库的一个模版
> > 
> > 
> > 依赖什么库，这里要加上
> 
> 系统库uikit也要吗？里面只是很简单的person类

参照Demo

**Comment by YaoJuan** [comment]
> 版

我感觉你在和我套娃，我我的私有库不依赖任何库，但是你的demo是有依赖的呀。我里面就是很干净的nsobject的类，为什么需要依赖呢

**Comment by YaoJuan** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/7920527/87649329-c00d6280-c782-11ea-9e77-73516c62fe6c.png)
> > > > > 这里少了
> > > > > 命令用的是 `pod bin auto --all-make`
> > > > > 命令我用的是pod bin auot --all-make。但是我这个库不依赖afn，也没有倒入afn，这只是创建私有库的一个模版
> > > 
> > > 
> > > 依赖什么库，这里要加上
> > 
> > 
> > 系统库uikit也要吗？里面只是很简单的person类
> 
> 参照Demo

请问是不是这个样子，我如果新建一个私有库，他依赖了ab cd，我如果用pod bin auto --all-make 只能把abcd打成二进制，自己本身并没有打成二进制zip包？我现在的实验是这个样子

**Comment by su350380433** [comment]
pod bin auto 是打包自己， --all-make 打包依赖所有依赖和自己

**Comment by YaoJuan** [comment]
> pod bin auto 是打包自己， --all-make 打包依赖所有依赖和自己

我现在是始终打包自己不成功，依赖是可以的。自己包本身永远没有生成对应的zip包，但是在archive文件夹里是有对应的.a静态库的。
![image](https://user-images.githubusercontent.com/16183272/87741850-12e52980-c818-11ea-8e61-7c86bae58df7.png)

![image](https://user-images.githubusercontent.com/16183272/87741958-4cb63000-c818-11ea-8aec-5747be6e6aa9.png)
这个mjextension是可以的

**Comment by YaoJuan** [comment]
而且demo中的demo这个私有库，也是制作自己不成功的。我已经把他自己从白名单拿出来了

**Comment by YaoJuan** [comment]
![image](https://user-images.githubusercontent.com/16183272/87743538-c4398e80-c81b-11ea-9832-f75ef329e05e.png)
我怀疑是不是合并架构的时候出错了呢，我看库自己的本身合并没有后续了。但是依赖的库是有后续的

**Comment by YaoJuan** [comment]
> pod bin auto 是打包自己， --all-make 打包依赖所有依赖和自己

能否有个教程创建一个新的私有库打成二进制呢？我这个问题卡了很久了。而且我这个私有库还是个demo，并没有什么复杂代码。主要目前报错也不明显，只是去文件夹发现已经生成了3个架构的静态库，但是没有合并成zip，也没有上传到服务器

**Comment by YaoJuan** [comment]
> pod bin auto 是打包自己， --all-make 打包依赖所有依赖和自己

请问是否能看看这个问题呢？我觉得这个问题应该不止我一个人遇到，肯定也有人和我一样调研会拿一个纯净的pod库来制作二进制库

**Comment by su350380433** [comment]
> ![image](https://user-images.githubusercontent.com/16183272/87743538-c4398e80-c81b-11ea-9832-f75ef329e05e.png)
> 我怀疑是不是合并架构的时候出错了呢，我看库自己的本身合并没有后续了。但是依赖的库是有后续的

提供更详细的的日志

**Comment by YaoJuan** [comment]
> > ![image](https://user-images.githubusercontent.com/16183272/87743538-c4398e80-c81b-11ea-9832-f75ef329e05e.png)
> > 我怀疑是不是合并架构的时候出错了呢，我看库自己的本身合并没有后续了。但是依赖的库是有后续的
> 
> 提供更详细的的日志

这已经是我最详细的日志了，加了--verbose了，库的源代码，源代码pod库仓库，二进制仓库都在我的repositories里

**Comment by su350380433** [comment]
> > > ![image](https://user-images.githubusercontent.com/16183272/87743538-c4398e80-c81b-11ea-9832-f75ef329e05e.png)
> > > 我怀疑是不是合并架构的时候出错了呢，我看库自己的本身合并没有后续了。但是依赖的库是有后续的
> > 
> > 
> > 提供更详细的的日志
> 
> 这已经是我最详细的日志了，加了--verbose了，库的源代码，源代码pod库仓库，二进制仓库都在我的repositories里

仅有这样的信息，我没法帮到你

**Comment by YaoJuan** [comment]
> > > > ![image](https://user-images.githubusercontent.com/16183272/87743538-c4398e80-c81b-11ea-9832-f75ef329e05e.png)
> > > > 我怀疑是不是合并架构的时候出错了呢，我看库自己的本身合并没有后续了。但是依赖的库是有后续的
> > > 
> > > 
> > > 提供更详细的的日志
> > 
> > 
> > 这已经是我最详细的日志了，加了--verbose了，库的源代码，源代码pod库仓库，二进制仓库都在我的repositories里
> 
> 仅有这样的信息，我没法帮到你

其实我觉得您可以建一个qq群，因为这个项目的确很好。而且您维护得也比较好，群里了的问题并不一定要你解决，毕竟人多力量大，大家可以一起互相讨论遇到的坑。互相补足

**Comment by su350380433** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/16183272/87743538-c4398e80-c81b-11ea-9832-f75ef329e05e.png)
> > > > > 我怀疑是不是合并架构的时候出错了呢，我看库自己的本身合并没有后续了。但是依赖的库是有后续的
> > > > 
> > > > 
> > > > 提供更详细的的日志
> > > 
> > > 
> > > 这已经是我最详细的日志了，加了--verbose了，库的源代码，源代码pod库仓库，二进制仓库都在我的repositories里
> > 
> > 
> > 仅有这样的信息，我没法帮到你
> 
> 其实我觉得您可以建一个qq群，因为这个项目的确很好。而且您维护得也比较好，群里了的问题并不一定要你解决，毕竟人多力量大，大家可以一起互相讨论遇到的坑。互相补足

用的人不够多啊
