### ISSUE TITLE
pod bin init error

### ISSUE THREAD

**Issue by cocoonbud** [MeetYouDevs/cocoapods-imy-bin#80]
hi 按照步骤pod bin init时，报错。请教下？

NameError - undefined method `podfile_for_spec' for class `Pod::Generate::PodfileGenerator'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/native/podfile_generator.rb:20:in `<class:PodfileGenerator>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/native/podfile_generator.rb:15:in `<module:Generate>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/native/podfile_generator.rb:12:in `<module:Pod>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/native/podfile_generator.rb:11:in `<top (required)>'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/native.rb:10:in `<top (required)>'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin.rb:46:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-imy-bin-0.3.0.11/lib/cocoapods-imy-bin/command/bin/init.rb:21:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by miroda** [comment]
sudo gem uninstall cocoapods-generate
sudo gem install cocoapods-generate -v 2.0.1

**Comment by dabing1022** [comment]
原因及解决方案：https://github.com/MeetYouDevs/cocoapods-imy-bin/issues/68

**Comment by dabing1022** [comment]
升级最新版 `0.3.1.3`

https://github.com/MeetYouDevs/cocoapods-imy-bin/releases/tag/0.3.1.3
