### ISSUE TITLE
默认Demo中使用pod bin auto出现 TypeError - no implicit conversion of nil into String错误

### ISSUE THREAD

**Issue by y2kbug** [MeetYouDevs/cocoapods-imy-bin#87]
/Users/xiong/Downloads/cocoapods-imy-bin-demo-master/Demo
/Users/xiong/Downloads/cocoapods-imy-bin-demo-master/binary-server
/Users/xiong/Downloads/cocoapods-imy-bin-demo-master/.DS_Store
/Users/xiong/Downloads/cocoapods-imy-bin-demo-master/Demo-build-temp
/Users/xiong/Downloads/cocoapods-imy-bin-demo-master/README.md
/Users/xiong/Downloads/cocoapods-imy-bin-demo-master/YYModel

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/xiong/.rvm/rubies/ruby-2.7.2/bin/pod bin auto
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
    RubyGems : 3.1.4
        Host : macOS 11.1 (20C69)
       Xcode : 12.2 (12B45b)
         Git : git version 2.28.0
Ruby lib dir : /Users/xiong/.rvm/rubies/ruby-2.7.2/lib
Repositories : guangqiang-liu - git - https://github.com/guangqiang-liu/GQSpec.git @ de49a111258dc3423bffcc68cd8a5d09fbb9daaf

               master - git - https://github.com/CocoaPods/Specs.git @ 54b47eac69d8bcfa0db967ad682fbb73d6c16c4a

               spec_bin - git - git@repo.we.com:turing.xiong/housekeeper_spec_bin_dev.git @ de9b38d309e49ffc1fd37682da8a1df4241032ca

               su350380433 - git - git@github.com:su350380433/example_spec_source.git @ 5a421ce7d5c61ff3cd761d44c751c72ccea3d3ff

               su350380433-1 - git - git@github.com:su350380433/example_spec_bin_dev.git @ 04a94cd20abe9ab0cf131b80ddbf35071ad044df

               trunk - CDN - https://cdn.cocoapods.org/
               TubatuRepo - git - git@repo.we.com:ios/tspecsrepo.git @ 009c9753d5a7aa1e7928d81f2d15a0e9a5bdfdce

```

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.1
cocoapods-imy-bin                     : 0.3.1.3
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
```

### Error

```
TypeError - no implicit conversion of nil into String
/Users/xiong/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `initialize'
/Users/xiong/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `new'
/Users/xiong/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:705:in `from_file'
/Users/xiong/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-imy-bin-0.3.1.3/lib/cocoapods-imy-bin/command/bin/auto.rb:33:in `initialize'
/Users/xiong/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `new'
/Users/xiong/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:356:in `parse'
/Users/xiong/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Users/xiong/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:352:in `parse'
/Users/xiong/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:330:in `run'
/Users/xiong/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/xiong/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/xiong/.rvm/rubies/ruby-2.7.2/bin/pod:23:in `load'
/Users/xiong/.rvm/rubies/ruby-2.7.2/bin/pod:23:in `<main>'
/Users/xiong/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
/Users/xiong/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=no+implicit+conversion+of+nil+into+String&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - TypeError - no implicit conversion of nil into String
   https://github.com/CocoaPods/CocoaPods/issues/10007 [closed] [5 comments]
   4 weeks ago

 - undefined method `map' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/9953 [closed] [1 comment]
   30 Jul 2020

 - TypeError - no implicit conversion of nil into String
   https://github.com/CocoaPods/CocoaPods/issues/6381 [closed] [17 comments]
   21 Mar 2020

and 21 more at:
https://github.com/cocoapods/cocoapods/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓

**Comment by y2kbug** [comment]
iterm2 bug

**Comment by zj159963** [comment]
> iterm2 bug

I meet the same question. But it still fail with Terminal.app .

**Comment by 13298897828** [comment]
+1,doesn't work with other Terminals
