### ISSUE TITLE
release_iphoneos环境设置完毕 但是执行pod bin auto --all-make还是显示dev环境

### ISSUE THREAD

**Issue by Joachim001** [MeetYouDevs/cocoapods-imy-bin#9]
set_configuration_env('')
是不是设置的话就按设置的来,不设置的话就按dev来？

**Comment by YaoJuan** [comment]
是的，这就是个默认值。后续你可以去~/.cocoapods/bin_xxx.yml去更改配置

**Comment by Joachim001** [comment]
按照作者的说法是有dev / debug_iphoneos / release_iphoneos三种编译环境的，三种编译环境的打出来的.a是不一样的，现在我遇到的问题是项目里设置了release_iphoneos且只有这个一个编译环境，打出来的.a支持x86_64，不是release_iphoneos编译环境的是dev的，有这个问题

**Comment by su350380433** [comment]
``` ruby
plugin 'cocoapods-imy-bin' 
set_configuration_env('release_iphoneos')
```
放在Podfile里面

**Comment by Joachim001** [comment]
放在Podfile里面，只是起到指定生产.a编译环境的作用吧，如果我使用了Podfile_local那在执行pod bin install的时候还要再次使用set_configuration_env在Podfile_local来指定我想要的编译环境吧？

**Comment by su350380433** [comment]
> 放在Podfile里面，起到是指定.a是debug还是release的作用吧，如果我使用了Podfile_local那在执行pod bin install的时候还要再次使用set_configuration_env在Podfile_local里来指定我想要的编译环境吧？

`plugin 'cocoapods-imy-bin' 
set_configuration_env('release_iphoneos')`
可以放到podfile_local,与podfile 同等效应

**Comment by Joachim001** [comment]
install/update的时候，放在podfile_local和podfile是同等效应。但是pod bin auto的时候，放在podfile里能改变编译环境，放在podfile_local里的话还是默认的dev改变不了

**Comment by su350380433** [comment]
> install/update的时候，放在podfile_local和podfile是同等效应。但是pod bin auto的时候，放在podfile里能改变编译环境，放在podfile_local里的话还是默认的dev改变不了

podfile_local和podfile是同等效应是为了方便开发时使用，但是制作二进制时还说以Podfile为准

**Comment by Joachim001** [comment]
在Podfile中设置了release_iphoneos，但是打出来的.a显示：Architectures in the fat file: /Users/XXX/Desktop/libKSCrash.a are: armv7 x86_64 arm64,我看文章上说release_iphoneos模式下不包含x86_64，那是不是制作二进制时指定编译环境没有生效呢？
