### ISSUE TITLE
适配问题

### ISSUE THREAD

**Issue by Denghuajie** [MeetYouDevs/cocoapods-imy-bin#98]
如果build for distribution设置为yes，很多子模块工程最低适配版本要改为iOS13.0以上，否则就会报类似的错：'@objc' instance method in extension of subclass of 'xxx' requires iOS 13.0.0，请问有没什么好的解决办法？

**Comment by dabing1022** [comment]
> 如果build for distribution设置为yes，很多子模块工程最低适配版本要改为iOS13.0以上

没太明白 能解释的更详细点么

**Comment by Denghuajie** [comment]
现在项目用的组件化，每个子模块单独打包成framework，然后导入进主工程进行运行或者打包app，之前是没有开启build for distribution这个选项的，所以每次升级xcode版本都要重新编译所有swift的库，包括子模块，现在开启之后，开源库编译没有问题，但是编译子模块的时候会报这个错误，提示要设置工程的最低适配版本，general->deployment info那里，如果设置为13.0以上就不会报错，但是这样就破坏app的系统版本兼容性了，有没其他方法？

**Comment by dabing1022** [comment]
这个问题应该和imy-bin没太大关系。
1. build for distribution说的是具体是什么？setting中的build libraries for distribution?
2. 子模块具体指的是什么？这个概念宽泛，不同团队不同人说法都不一样，可以具体说下

**Comment by Denghuajie** [comment]
1.说的是setting中的build libraries for distribution没错
2.子模块，可以理解为某个组件，单独编译成framework给壳工程使用

**Comment by Denghuajie** [comment]
我们的子模块是单独的project，编译成framework后，导入进主工程

**Comment by Denghuajie** [comment]
可以参考下这里：https://developer.apple.com/forums/thread/120352

**Comment by dabing1022** [comment]
大概明白了 这个是Swift ABI兼容相关性的问题。暂时没太多这方面的经验不能帮助到你。

**Comment by Denghuajie** [comment]
很好奇，苹果官方不是说swift abi稳定了吗，怎么还会有这种问题

**Comment by Denghuajie** [comment]
> 大概明白了 这个是Swift ABI兼容相关性的问题。暂时没太多这方面的经验不能帮助到你。

您好，已经编译成功了，但是放到低版本的xcode去编译不报错，building tasks的时候一直卡住了，请问是什么问题？

**Comment by xiushaomin** [comment]
> Denghuajie

这个编译问题是怎么绕过的啊？

**Comment by xiushaomin** [comment]
> > 大概明白了 这个是Swift ABI兼容相关性的问题。暂时没太多这方面的经验不能帮助到你。
> 
> 您好，已经编译成功了，但是放到低版本的xcode去编译不报错，building tasks� 的时候一直卡住了，请问是什么问题？

这个问题是怎么绕过去的啊？
